-- =============================================================================
-- Automation Interface - Database Schema Reference
-- Run sections as needed. Existing migrations 001-003 may have created some tables.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. automation_users
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS automation_users (
  id BIGSERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE automation_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Block anon access" ON automation_users
  FOR ALL
  USING (false)
  WITH CHECK (false);

CREATE INDEX IF NOT EXISTS idx_automation_users_email ON automation_users(email);


-- -----------------------------------------------------------------------------
-- 2. client_details
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS client_details (
  id BIGSERIAL PRIMARY KEY,
  client_tag TEXT NOT NULL,
  locations TEXT,
  zip_codes TEXT,
  zip_codes_format TEXT[],
  business_categories TEXT[],
  allowed_types TEXT[],
  drive_url TEXT,
  process_automations BOOLEAN NOT NULL DEFAULT false,
  query_created BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migration for existing deployments:
ALTER TABLE client_details
  ADD COLUMN IF NOT EXISTS business_categories TEXT[];

ALTER TABLE client_details
  ADD COLUMN IF NOT EXISTS allowed_types TEXT[];

ALTER TABLE client_details ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Block anon access" ON client_details
  FOR ALL
  USING (false)
  WITH CHECK (false);

CREATE INDEX IF NOT EXISTS idx_client_details_client_tag ON client_details(client_tag);


-- -----------------------------------------------------------------------------
-- 3. automation_logs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS automation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_tag TEXT,
  processing_ids BIGINT[],
  pending_ids BIGINT[],
  status TEXT DEFAULT 'processing',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'Asia/Kolkata'),
  drive_file TEXT
);


-- -----------------------------------------------------------------------------
-- 4. bulk_insert_client_queries RPC
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION bulk_insert_client_queries(
  p_client_tag TEXT,
  p_region TEXT,
  p_queries TEXT[],
  p_latitudes TEXT[],
  p_longitudes TEXT[]
)
RETURNS JSON AS $$
DECLARE
  v_inserted_count INTEGER;
  v_array_length INTEGER;
BEGIN
  -- Validate array lengths match
  v_array_length := array_length(p_queries, 1);

  IF v_array_length != array_length(p_latitudes, 1) OR
     v_array_length != array_length(p_longitudes, 1) THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Array lengths do not match',
      'inserted_count', 0
    );
  END IF;

  -- Insert all queries with coordinates in a single operation
  INSERT INTO client_queries (client_tag, query, latitude, longitude, mode, status, region)
  SELECT
    p_client_tag,
    unnest(p_queries),
    unnest(p_latitudes)::numeric,
    unnest(p_longitudes)::numeric,
    'auto',
    'not_used',
    p_region;

  -- Get the number of inserted rows
  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

  -- Return result as JSON
  RETURN json_build_object(
    'success', true,
    'inserted_count', v_inserted_count
  );

EXCEPTION WHEN OTHERS THEN
  -- Return error information
  RETURN json_build_object(
    'success', false,
    'error', SQLERRM
  );
END;
$$ LANGUAGE plpgsql;


-- -----------------------------------------------------------------------------
-- 5. change_not_used_to_auto_queued RPC
-- Updates client_queries from 'not_used' to 'auto_queued' and sets automation_id
-- Usage: select change_not_used_to_auto_queued('tag_A', p_batch_size, p_automation_id);
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION change_not_used_to_auto_queued(
  p_client_tag TEXT,
  p_batch_size INT,
  p_automation_id BIGINT
)
RETURNS JSON
LANGUAGE plpgsql
AS $$
DECLARE
  v_result JSON;
BEGIN
  WITH updated_rows AS (
    UPDATE client_queries
    SET
      status = 'auto_queued',
      automation_id = p_automation_id
    WHERE id IN (
      SELECT q.id
      FROM client_queries q
      WHERE q.client_tag = p_client_tag
        AND q.status = 'not_used'
      ORDER BY q.created_at
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    RETURNING id
  )
  SELECT json_build_object(
    'client_tag', p_client_tag,
    'processing_ids', COALESCE(array_agg(id::text), '{}'::text[])
  ) INTO v_result
  FROM updated_rows;

  RETURN v_result;
END;
$$;


-- =============================================================================
-- OTHER REQUIRED TABLES (create separately; schema not included)
-- =============================================================================
--
-- client_queries
--   Required columns: id, client_tag, query, latitude, longitude, mode, status,
--   region, automation_id (FK to automation_logs.id, nullable initially)
--   Used by: bulk_insert_client_queries, client-queries-count API, automation-status API
--   Status values: 'not_used', 'auto_queued', 'auto_completed', etc.
--
-- client_query_results
--   Required columns: id, automation_id, gpt_process
--   Used by: automation-status API
--   gpt_process values: 'auto_completed' = done, others = pending
--
-- email_scraper_node
--   Required columns: id, automation_id, status
--   Used by: automation-status API
--   status values: 'auto_final_completed' = done, others = pending
--

