export const BUSINESS_CATEGORIES: string[] = [
  "Village hall",
  "Hotel management school",
  "Yoga retreat center",
  "Hotel supply store",
  "Apartment building",
  "Furnished apartment building",
  "Farmstay",
  "Apartment complex",
  "Capsule hotel",
  "Casino hotel",
  "Extended stay hotel",
  "Health resort",
  "Holiday apartment rental",
  "Hostel",
  "Hotel",
  "Love hotel",
  "Motel",
  "Pilgrim hostel",
  "Resort hotel",
  "Serviced accommodation",
  "Serviced apartment",
  "Ski resort",
  "Villa",
  "Wellness hotel",
  "Working women's hostel",
  "Youth hostel",
  "Retreat center",
  "Convention center",
  "Greyhound stadium",
  "Stadium",
  "Pool hall",
  "Vauxhall dealer",
  "Ballroom dance instructor",
  "Auditorium",
  "Banquet hall",
  "Beer hall",
  "Bingo hall",
  "Children hall",
  "City or town hall",
  "Concert hall",
  "Curling hall",
  "Dance hall",
  "Festival hall",
  "Jehovah's Witness Kingdom Hall",
  "Philharmonic hall",
  "Scout hall",
  "Function room facility",
  "Event venue",
  "Wedding venue",
  "Civic center",
  "Community center",
  "Conference center",
  "Cultural center",
  "Physical examination center",
  "Church supply store",
  "Church council office",
  "Vineyard church",
  "Bahá'í house of worship",
  "Hispanic church",
  "Abbey",
  "Abundant Life church",
  "Alliance church",
  "Anglican church",
  "Apostolic church",
  "Armenian church",
  "Ashram",
  "Assemblies of God church",
  "Baptist church",
  "Basilica",
  "Buddhist temple",
  "Calvary Chapel church",
  "Catholic church",
  "Chapel",
  "Christian church",
  "Church",
  "Church of Christ",
  "Church of Jesus Christ of Latter-day Saints",
  "Church of the Nazarene",
  "City pillar shrine",
  "Conservative synagogue",
  "Deaf church",
  "Disciples of Christ Church",
  "Eastern Orthodox Church",
  "Episcopal church",
  "Evangelical church",
  "Foursquare church",
  "Friends church",
  "Full Gospel church",
  "Gospel church",
  "Greek Orthodox church",
  "Hindu temple",
  "Jain temple",
  "Korean church",
  "Lutheran church",
  "Mennonite church",
  "Messianic synagogue",
  "Methodist church",
  "Moravian church",
  "Mosque",
  "New Age church",
  "Non-denominational church",
  "Orthodox church",
  "Orthodox synagogue",
  "Pagoda",
  "Parsi temple",
  "Pentecostal church",
  "Place of worship",
  "Presbyterian church",
  "Protestant church",
  "Quaker church",
  "Reform synagogue",
  "Reformed church",
  "Russian Orthodox church",
  "Seventh-day Adventist church",
  "Shinto shrine",
  "Shrine",
  "Synagogue",
  "Taoist temple",
  "Unitarian Universalist Church",
  "United Church of Canada",
  "United Church of Christ",
  "United Methodist church",
  "Unity church",
  "Wedding chapel",
  "Wesleyan church",
  "Cathedral",
  "Catholic cathedral",
  "Convention information bureau",
  "Monastery",
  "Convent",
  "Gymnasium school",
  "Vocational gymnasium school",
  "Martial arts school",
  "Adult education school",
  "General education school",
  "Special education school",
  "Baby swimming school",
  "Swimming school",
  "Barber school",
  "Bartending school",
  "Modeling school",
  "School cafeteria",
  "Hospitality and tourism school",
  "Student dormitory",
  "School supply store",
  "Hospitality high school",
  "Nursery school",
  "Architecture school",
  "Charter school",
  "Law school",
  "Music school",
  "Wrestling school",
  "Farm school",
  "Real estate school",
  "School house",
  "Study at home school",
  "Massage school",
  "Cue sports school",
  "Sports school",
  "Accounting school",
  "Acupuncture school",
  "After school program",
  "Agricultural high school",
  "Aikido school",
  "Art school",
  "Ballet school",
  "Beauty school",
  "Berufsfachschule (vocational school with apprenticeship)",
  "Bilingual preschool",
  "Bilingual school",
  "School for the visually impaired",
  "Boarding school",
  "Boys' high school",
  "Business school",
  "Capoeira school",
  "Catholic school",
  "CBSE school",
  "Chinese language school",
  "Co-ed school",
  "Combined primary and secondary school",
  "Community school",
  "Comprehensive secondary school",
  "Computer training school",
  "Cooking school",
  "Cramming school",
  "Culinary school",
  "Dance school",
  "Dental school",
  "Drama school",
  "Drivers license training school",
  "Driving school",
  "Drum school",
  "Elementary school",
  "Emergency training school",
  "Engineering school",
  "English language school",
  "Evening school",
  "Fashion design school",
  "Fencing school",
  "Flamenco school",
  "Flight school",
  "Folk high school",
  "Foreign languages program school",
  "French language school",
  "German language school",
  "Girls' high school",
  "Government school",
  "Graduate school",
  "Grammar school",
  "Handicraft school",
  "Hauptschule (lower-tier secondary school)",
  "High school",
  "Higher secondary school",
  "Horse riding school",
  "ICSE school",
  "International school",
  "Judo school",
  "Jujitsu school",
  "K-12 school",
  "Karate school",
  "Kickboxing school",
  "Kung fu school",
  "Language school",
  "Management school",
  "Mathematics school",
  "Medical school",
  "Middle school",
  "Military school",
  "Montessori preschool",
  "Montessori school",
  "Motorcycle driving school",
  "Nursing school",
  "Parochial school",
  "Photography school",
  "Preparatory school",
  "Preschool",
  "Primary school",
  "Realschule (middle-tier secondary school)",
  "Religious school",
  "Sailing school",
  "Samba school",
  "Sambo school",
  "School",
  "School administration office",
  "School bus service",
  "School center",
  "School district office",
  "School for the deaf",
  "Secondary school",
  "Self defense school",
  "Senior high school",
  "Single sex secondary school",
  "Ski school",
  "Surf school",
  "Taekwondo school",
  "Tai chi school",
  "Technical school",
  "Telecommunication school",
  "Trade school",
  "Truck driving school",
  "Vocational secondary school",
  "Vocational school",
  "Waldorf school",
  "Wing chun school",
  "Athletic track",
  "Athletic field",
  "Martial arts supply store",
  "Aerobics instructor",
  "Bikram yoga studio",
  "Pilates studio",
  "Yoga studio",
  "Cycling park",
  "Gymnastics club",
  "Boxing gym",
  "Clergyman",
  "Gym",
  "Gymnastics center",
  "Indoor cycling",
  "Muay Thai boxing gym",
  "Rock climbing gym",
  "Athletic club",
  "Athletic park",
  "Boxing club",
  "Martial arts club",
  "Boxing ring",
  "Fitness center",
  "Physical fitness program",
  "Weightlifting area",
  "Public educational institution",
  "Public university",
  "Corporate campus",
  "Educational supply store",
  "University hospital",
  "Faculty of pharmacy",
  "Educational consultant",
  "Music college",
  "Christian college",
  "Institute of Geography and Statistics",
  "Police academy",
  "College of agriculture",
  "Aviation training institute",
  "Board of education",
  "College",
  "Community college",
  "Design institute",
  "Education center",
  "Educational institution",
  "Educational testing service",
  "Financial institution",
  "Fire fighters academy",
  "Firearms academy",
  "Government college",
  "Institute of technology",
  "Junior college",
  "Land reform institute",
  "Ministry of Education",
  "Open university",
  "Polytechnic institute",
  "Private college",
  "Private educational institution",
  "Private university",
  "Research institute",
  "Residential college",
  "Sixth form college",
  "Software training institute",
  "State office of education",
  "Teachers college",
  "Technical university",
  "University",
  "University library",
  "Women's college",
  "Faculty of law",
  "Conservatory of music",
  "Music conservatory",
  "Faculty of science",
  "Public swimming pool",
  "Public golf course",
  "Swimming pool supply store",
  "Baseball goods store",
  "Golf shop",
  "Hockey supply store",
  "Soccer store",
  "Golf cart dealer",
  "Basketball court contractor",
  "Swimming pool contractor",
  "Golf course builder",
  "Golf instructor",
  "Swimming instructor",
  "Volleyball instructor",
  "Rugby field",
  "Indoor playground",
  "Playground",
  "Playground equipment supplier",
  "Rugby club",
  "Arena",
  "Ice hockey rink",
  "Ice skating rink",
  "Racecourse",
  "Roller skating rink",
  "Badminton court",
  "Basketball court",
  "Beach volleyball court",
  "Bocce ball court",
  "Futsal court",
  "Handball court",
  "Padel court",
  "Pickleball court",
  "Squash court",
  "Tennis court",
  "Tennis court construction company",
  "Volleyball court",
  "Baseball field",
  "American football field",
  "Hockey field",
  "Horse riding field",
  "Little league field",
  "Soccer field",
  "Softball field",
  "Swimming lake",
  "Cricket ground",
  "Acrobatic diving pool",
  "Archery club",
  "Baseball club",
  "Basketball club",
  "Beach volleyball club",
  "BMX club",
  "BMX park",
  "Cricket club",
  "Football club",
  "Golf club",
  "Hockey club",
  "Ice hockey club",
  "Ice skating club",
  "Indoor swimming pool",
  "Outdoor swimming pool",
  "Pool billard club",
  "Roller skating club",
  "Soccer club",
  "Softball club",
  "Swimming pool",
  "Swimming pool repair service",
  "Table tennis club",
  "Tennis club",
  "Volleyball club",
  "Water polo pool",
  "Water skiing club",
  "Sports complex",
  "Badminton complex",
  "Disc golf course",
  "Golf course",
  "Golf driving range",
  "Indoor golf course",
  "Miniature golf course",
  "Private golf course",
  "Soccer practice",
  "Swimming basin",
  "Swimming competition",
  "Swimming facility",
  "Table tennis facility",
  "Finnish restaurant",
  "Bar restaurant furniture store",
  "Barber shop",
  "Barber supply store",
  "Butcher shop deli",
  "Grill store",
  "Grocery delivery service",
  "Restaurant supply store",
  "Small plates restaurant",
  "Abarth dealer",
  "Acaraje restaurant",
  "Caribbean restaurant",
  "Nicaraguan restaurant",
  "Subaru dealer",
  "Bariatric surgeon",
  "Hyperbaric medicine physician",
  "Classified ads newspaper publisher",
  "Certified public accountant",
  "Public sector bank",
  "Barrister",
  "Modeling agency",
  "South Sulawesi restaurant",
  "Karaoke bar",
  "Live music bar",
  "Music publisher",
  "Printed music publisher",
  "Public bathroom",
  "Public female bathroom",
  "Public housing",
  "Public male bathroom",
  "Public wheelchair-accessible bathroom",
  "Public parking space",
  "Public sauna",
  "Department of Public Safety",
  "Notary public",
  "Public bath",
  "Public defender's office",
  "Public health department",
  "Public library",
  "Public medical center",
  "Public prosecutors office",
  "Public relations firm",
  "Public safety office",
  "Public utility company",
  "Public water well",
  "Public works department",
  "Super public bath",
  "Chophouse restaurant",
  "French steakhouse restaurant",
  "Japanese steakhouse",
  "Traditional teahouse",
  "Cabaret club",
  "Newspaper publisher",
  "Spanish restaurant",
  "Portuguese restaurant",
  "Sports bar",
  "Dumpling restaurant",
  "Afghan restaurant",
  "African restaurant",
  "Algerian Restaurant",
  "Alsace restaurant",
  "American restaurant",
  "Anhui restaurant",
  "Anago restaurant",
  "Andalusian restaurant",
  "Andhra restaurant",
  "Angler fish restaurant",
  "Animal cafe",
  "Arab restaurant",
  "Argentinian restaurant",
  "Armenian restaurant",
  "Army barracks",
  "Art cafe",
  "Grill",
  "Asian fusion restaurant",
  "Asian restaurant",
  "Assamese restaurant",
  "Asturian restaurant",
  "Australian restaurant",
  "Austrian restaurant",
  "Awadhi restaurant",
  "Ayam penyet restaurant",
  "Azerbaijani restaurant",
  "Baden restaurant",
  "Bakery",
  "Bakery equipment",
  "Bakso restaurant",
  "Balinese restaurant",
  "Bangladeshi restaurant",
  "Bar",
  "Bar & grill",
  "Bar PMU",
  "Bar stool supplier",
  "Bar tabac",
  "Barbecue restaurant",
  "Barbecue area",
  "Bark supplier",
  "Barrel supplier",
  "Bartending service",
  "Basque restaurant",
  "Batak restaurant",
  "Bavarian restaurant",
  "Bed & breakfast",
  "Gyudon restaurant",
  "Belgian restaurant",
  "Bengali restaurant",
  "Berry restaurant",
  "Betawi restaurant",
  "Biryani restaurant",
  "Bistro",
  "Book publisher",
  "Brazilian pastelaria",
  "Brazilian restaurant",
  "Breakfast restaurant",
  "Brewery",
  "Brewpub",
  "British restaurant",
  "Brunch restaurant",
  "Buffet restaurant",
  "Bulgarian restaurant",
  "Burmese restaurant",
  "Burrito restaurant",
  "Cafe",
  "Cafeteria",
  "Cajun restaurant",
  "Californian restaurant",
  "Cambodian restaurant",
  "Pacific Northwest restaurant (Canada)",
  "Canadian restaurant",
  "Cantabrian restaurant",
  "Cantonese restaurant",
  "Cape Verdean restaurant",
  "Castilian restaurant",
  "Syokudo and Teishoku restaurant",
  "Conveyor belt sushi restaurant",
  "Cat cafe",
  "Catalonian restaurant",
  "Caucasian restaurant",
  "Cendol restaurant",
  "Central American restaurant",
  "Central European restaurant",
  "Central Javanese restaurant",
  "Champon noodle restaurant",
  "Chanko restaurant",
  "Charcuterie",
  "Cheesesteak restaurant",
  "Chesapeake restaurant",
  "Chettinad restaurant",
  "Chicken restaurant",
  "Chicken wings restaurant",
  "Children's cafe",
  "Children's party buffet",
  "Chilean restaurant",
  "Chinese noodle restaurant",
  "Chinese bakery",
  "Chinese restaurant",
  "Chinese takeaway",
  "Chocolate cafe",
  "Chop bar",
  "Churreria",
  "Cider bar",
  "Cig kofte restaurant",
  "Cocktail bar",
  "Cold noodle restaurant",
  "Colombian restaurant",
  "Comic cafe",
  "Contemporary Louisiana restaurant",
  "Continental restaurant",
  "Cosplay cafe",
  "Costa Rican restaurant",
  "Country food restaurant",
  "Couscous restaurant",
  "Creole restaurant",
  "Creperie",
  "Croatian restaurant",
  "Cuban restaurant",
  "Cured ham bar",
  "Czech restaurant",
  "Dan Dan noodle restaurant",
  "Dance restaurant",
  "Danish restaurant",
  "Dart bar",
  "Deli",
  "Delivery Chinese restaurant",
  "Delivery service",
  "Desktop publishing service",
  "Sweets and dessert buffet",
  "Dessert restaurant",
  "Dhaba",
  "Dim sum restaurant",
  "Diner",
  "Dog cafe",
  "Dojo restaurant",
  "Dominican restaurant",
  "Donburi restaurant",
  "Doner kebab restaurant",
  "Durum restaurant",
  "Dutch restaurant",
  "East African restaurant",
  "East Javanese restaurant",
  "Eastern European restaurant",
  "Eclectic restaurant",
  "Ecuadorian restaurant",
  "Egyptian restaurant",
  "English restaurant",
  "Eritrean restaurant",
  "Espresso bar",
  "Ethiopian restaurant",
  "European restaurant",
  "Extremaduran restaurant",
  "Eyebrow bar",
  "Falafel restaurant",
  "Family restaurant",
  "Fast food restaurant",
  "Filipino restaurant",
  "Fine dining restaurant",
  "Fish & chips restaurant",
  "Fish and chips takeaway",
  "Fish restaurant",
  "Floridian restaurant",
  "Flower delivery",
  "Fondue restaurant",
  "Franconian restaurant",
  "French restaurant",
  "Fried chicken takeaway",
  "Frituur",
  "Fujian restaurant",
  "Fugu restaurant",
  "Fusion restaurant",
  "Galician restaurant",
  "Gastropub",
  "Gay bar",
  "Georgian restaurant",
  "German restaurant",
  "Girl bar",
  "Gluten-free restaurant",
  "Goan restaurant",
  "Greek restaurant",
  "Guatemalan restaurant",
  "Guizhou restaurant",
  "Gujarati restaurant",
  "Offal barbecue restaurant",
  "Gyro restaurant",
  "Haitian restaurant",
  "Hakka restaurant",
  "Halal restaurant",
  "Haleem restaurant",
  "Hamburger restaurant",
  "Haute French restaurant",
  "Hawaiian restaurant",
  "Health food restaurant",
  "Hoagie restaurant",
  "Honduran restaurant",
  "Cha chaan teng (Hong Kong-style cafe)",
  "Hong Kong style fast food restaurant",
  "Hookah bar",
  "Hot dog restaurant",
  "Hot pot restaurant",
  "Hunan restaurant",
  "Hungarian restaurant",
  "Hyderabadi restaurant",
  "Icelandic restaurant",
  "Ikan bakar restaurant",
  "Indian Muslim restaurant",
  "Indian restaurant",
  "Indian sizzler restaurant",
  "Indian takeaway",
  "Indonesian restaurant",
  "Internet cafe",
  "Irish pub",
  "Irish restaurant",
  "Israeli restaurant",
  "Italian restaurant",
  "Jamaican restaurant",
  "Authentic Japanese restaurant",
  "Japanese curry restaurant",
  "Japanese delicatessen",
  "Ryotei restaurant",
  "Izakaya restaurant",
  "Japanese regional restaurant",
  "Japanese restaurant",
  "Japanese sweets restaurant",
  "Japanized western restaurant",
  "Javanese restaurant",
  "Jewish restaurant",
  "Jiangsu restaurant",
  "Kaiseki restaurant",
  "Kalle pache restaurant",
  "Karnataka restaurant",
  "Kashmiri restaurant",
  "Kazakhstani restaurant",
  "Kerala restaurant",
  "Kofta restaurant",
  "Konkani restaurant",
  "Korean barbecue restaurant",
  "Korean beef restaurant",
  "Korean restaurant",
  "Korean rib restaurant",
  "Koshari restaurant",
  "Kosher restaurant",
  "Kushiyaki restaurant",
  "Kyoto style Japanese restaurant",
  "Laotian restaurant",
  "Latin American restaurant",
  "Lebanese restaurant",
  "Lechon restaurant",
  "Lesbian bar",
  "Ligurian restaurant",
  "Lithuanian restaurant",
  "Lombardian restaurant",
  "Lunch restaurant",
  "Macrobiotic restaurant",
  "Madrilian restaurant",
  "Majorcan restaurant",
  "Malaysian restaurant",
  "Maltese restaurant",
  "Manado restaurant",
  "Mandarin restaurant",
  "Marathi restaurant",
  "Marche restaurant",
  "Meal delivery",
  "Takeout restaurant",
  "Meat dish restaurant",
  "Mediterranean restaurant",
  "Mexican restaurant",
  "Mexican torta restaurant",
  "Meyhane",
  "Mid-Atlantic restaurant (US)",
  "Middle Eastern restaurant",
  "Military barracks",
  "Milk delivery service",
  "Miso cutlet restaurant",
  "Modern British restaurant",
  "Modern European restaurant",
  "Modern French restaurant",
  "Modern Indian restaurant",
  "Momo restaurant",
  "Mongolian barbecue restaurant",
  "Monjayaki restaurant",
  "Modern izakaya restaurant",
  "Moroccan restaurant",
  "Mughlai restaurant",
  "Multimedia and electronic book publisher",
  "Murtabak restaurant",
  "Mutton barbecue restaurant",
  "Nasi goreng restaurant",
  "Nasi restaurant",
  "Nasi uduk restaurant",
  "Native American restaurant",
  "Navarraise restaurant",
  "Neapolitan restaurant",
  "Nepalese restaurant",
  "New England restaurant",
  "New American restaurant",
  "New Zealand restaurant",
  "Non vegetarian restaurant",
  "North African restaurant",
  "North Eastern Indian restaurant",
  "North Indian restaurant",
  "Northern Italian restaurant",
  "Norwegian restaurant",
  "Nuevo Latino restaurant",
  "Nyonya restaurant",
  "Oaxacan restaurant",
  "Obanzai restaurant",
  "Oden restaurant",
  "Odia restaurant",
  "Offal pot cooking restaurant",
  "Okonomiyaki restaurant",
  "Organic restaurant",
  "Oyster bar restaurant",
  "Pacific Rim restaurant",
  "Padang restaurant",
  "Paisa restaurant",
  "Pakistani restaurant",
  "Palatine restaurant",
  "Palestinian restaurant",
  "Pan-Asian restaurant",
  "Pan-Latin restaurant",
  "Pancake restaurant",
  "Paraguayan restaurant",
  "Parsi restaurant",
  "Patisserie",
  "Pay by weight restaurant",
  "Pecel lele restaurant",
  "Pempek restaurant",
  "Pennsylvania Dutch restaurant",
  "Persian restaurant",
  "Peruvian restaurant",
  "Pho restaurant",
  "Piadina restaurant",
  "Piano bar",
  "Piedmontese restaurant",
  "Pilaf restaurant",
  "Pizza delivery",
  "Pizza restaurant",
  "Pizza takeaway",
  "Po’ boys restaurant",
  "Poke bar",
  "Polish restaurant",
  "Polynesian restaurant",
  "Katsudon restaurant",
  "Porridge restaurant",
  "Pozole restaurant",
  "Provence restaurant",
  "Pub",
  "Publisher",
  "Pueblan restaurant",
  "Puerto Rican restaurant",
  "Punjabi restaurant",
  "Québécois restaurant",
  "Queer bar",
  "Raclette restaurant",
  "Rajasthani restaurant",
  "Ramen restaurant",
  "Raw food restaurant",
  "Restaurant",
  "Brasserie",
  "Rice restaurant",
  "Roman restaurant",
  "Romanian restaurant",
  "Russian restaurant",
  "Sake brewery",
  "Salsa bar",
  "Salvadoran restaurant",
  "Sambodrome",
  "Sardinian restaurant",
  "Satay restaurant",
  "Scandinavian restaurant",
  "Scottish restaurant",
  "Seafood donburi restaurant",
  "Seafood restaurant",
  "Seblak restaurant",
  "Self service restaurant",
  "Serbian restaurant",
  "Seychelles restaurant",
  "Sfiha restaurant",
  "Sukiyaki and Shabu Shabu restaurant",
  "Shabu-shabu restaurant",
  "Shandong restaurant",
  "Shanghainese restaurant",
  "Shawarma restaurant",
  "Shochu brewery",
  "Sichuan restaurant",
  "Sicilian restaurant",
  "Singaporean restaurant",
  "Kushiage and kushikatsu restaurant",
  "Snack bar",
  "Soapland",
  "Suppon restaurant",
  "Soondae restaurant",
  "Soto ayam restaurant",
  "Soto restaurant",
  "Soul food restaurant",
  "Soup restaurant",
  "South African restaurant",
  "South American restaurant",
  "South Asian restaurant",
  "Southeast Asian restaurant",
  "South Indian restaurant",
  "Southern Italian restaurant",
  "Southern restaurant (US)",
  "Southwest France restaurant",
  "Southwestern restaurant (US)",
  "Sri Lankan restaurant",
  "Stand bar",
  "Steamboat restaurant",
  "Sukiyaki restaurant",
  "Sundae restaurant",
  "Sundanese restaurant",
  "Surinamese restaurant",
  "Sushi restaurant",
  "Sushi takeaway",
  "Swabian restaurant",
  "Swedish restaurant",
  "Swiss restaurant",
  "Syrian restaurant",
  "Tabascan restaurant",
  "Tacaca restaurant",
  "Taco restaurant",
  "Taiwanese restaurant",
  "Takoyaki restaurant",
  "Tapas bar",
  "Tapas restaurant",
  "Tegal restaurant",
  "Temaki restaurant",
  "Tempura donburi restaurant",
  "Tempura restaurant",
  "Teppanyaki restaurant",
  "Tex-Mex restaurant",
  "Thai restaurant",
  "Thuringian restaurant",
  "Tibetan restaurant",
  "Tiki bar",
  "Toast restaurant",
  "Tofu restaurant",
  "Tongue restaurant",
  "Tonkatsu restaurant",
  "Traditional American restaurant",
  "Tunisian restaurant",
  "Turkish restaurant",
  "Turkmen restaurant",
  "Tuscan restaurant",
  "Udon noodle restaurant",
  "Ukrainian restaurant",
  "Unagi restaurant",
  "Uruguayan restaurant",
  "Pacific Northwest restaurant (US)",
  "Uyghur cuisine restaurant",
  "Uzbeki restaurant",
  "Valencian restaurant",
  "Vegan restaurant",
  "Vegetarian cafe and deli",
  "Vegetarian restaurant",
  "Venetian restaurant",
  "Venezuelan restaurant",
  "Vietnamese restaurant",
  "Wedding bakery",
  "Wedding buffet",
  "Welsh restaurant",
  "West African restaurant",
  "Western restaurant",
  "Wholesale bakery",
  "Wine bar",
  "Wok restaurant",
  "Yakiniku restaurant",
  "Yakisoba Restaurant",
  "Yakitori restaurant",
  "Yemeni restaurant",
  "Yucatan restaurant",
  "Zhejiang restaurant",
  "Cabinet store",
  "Camping store",
  "Cabinet maker",
  "Sport tour agency",
  "Apartment rental agency",
  "Balloon ride tour agency",
  "Boat tour agency",
  "Bus tour agency",
  "Cabin rental agency",
  "Canoe & kayak tour agency",
  "Helicopter tour agency",
  "SCUBA tour agency",
  "Short term apartment rental agency",
  "Sightseeing tour agency",
  "Tour agency",
  "Whale watching tour agency",
  "Dinner theater",
  "Farm household tour",
  "Camping farm",
  "Campground",
  "Military residence",
  "Boot camp",
  "Children's camp",
  "Camper shell supplier",
  "Camping cabin",
  "Chalet",
  "English language camp",
  "Fishing camp",
  "Inn",
  "Lodge",
  "Lodging",
  "Log cabins",
  "Mountain cabin",
  "Municipal Department of Tourism",
  "Observatory",
  "Planetarium",
  "Refugee camp",
  "Religious destination",
  "Religious lodging",
  "Summer camp organizer",
  "Tour operator",
  "Tourist attraction",
  "Tourist information center",
  "Holiday apartment",
  "Yakatabune",
  "Sports card store",
  "Auto care products store",
  "Car accessories store",
  "Car battery store",
  "Car stereo store",
  "Carpet store",
  "Carpet wholesaler",
  "Cash and carry wholesaler",
  "Greeting card shop",
  "Racing car parts store",
  "Trading card store",
  "Building materials market",
  "Building materials store",
  "Garden building supplier",
  "Machine workshop",
  "Metal workshop",
  "Millwork shop",
  "Parapharmacy",
  "Architectural salvage store",
  "Law book store",
  "Lawn mower store",
  "Marketing agency",
  "Marketing consultant",
  "Home theater store",
  "Music box store",
  "Music store",
  "Musical instrument repair shop",
  "Musical instrument store",
  "Sheet music store",
  "Theater supply store",
  "Used musical instrument store",
  "Off track betting shop",
  "Rugby store",
  "Soft drinks shop",
  "Christian book store",
  "Christmas market",
  "Christmas store",
  "Stationery store",
  "Stationery wholesaler",
  "Police supply store",
  "Botanical garden",
  "Farm shop",
  "Farmers' market",
  "Orchard",
  "Silk plant shop",
  "Warehouse store",
  "Asian household goods store",
  "Baby clothing store",
  "Bathroom supply store",
  "Batik clothing store",
  "Beach clothing store",
  "Bedroom furniture store",
  "Children's clothing store",
  "Clothes and fabric wholesaler",
  "Clothes market",
  "Clothing store",
  "Clothing wholesale market place",
  "Clothing wholesaler",
  "Home goods store",
  "Home improvement store",
  "Household goods wholesaler",
  "Lottery retailer",
  "Lottery shop",
  "Men's clothing store",
  "Mobile home supply store",
  "Outdoor clothing and equipment shop",
  "Plus size clothing store",
  "Showroom",
  "Home audio store",
  "Tesla showroom",
  "Transmission shop",
  "Used clothing store",
  "Vintage clothing store",
  "Wholesaler household appliances",
  "Women's clothing store",
  "Work clothes store",
  "Youth clothing store",
  "Massage supply store",
  "Sauna store",
  "Spa garden",
  "Body piercing shop",
  "Motorsports store",
  "Outdoor sports store",
  "Sporting goods store",
  "Sports accessories wholesaler",
  "Sports memorabilia store",
  "Sports nutrition store",
  "Sportswear store",
  "Tattoo and piercing shop",
  "Wine wholesaler and importer",
  "Açaí shop",
  "Acrylic store",
  "Adult DVD store",
  "Adult entertainment store",
  "Aeromodel shop",
  "African goods store",
  "Agricultural product wholesaler",
  "Air conditioning store",
  "Airbrushing supply store",
  "Aircraft supply store",
  "Airsoft supply store",
  "Alcoholic beverage wholesaler",
  "American grocery store",
  "Amish furniture store",
  "Antique furniture store",
  "Antique store",
  "Appliance store",
  "Appliances customer service",
  "Aquarium shop",
  "Archery store",
  "Army & navy surplus shop",
  "Aromatherapy supply store",
  "Art supply store",
  "Asian grocery store",
  "ATV repair shop",
  "Australian goods store",
  "Auto accessories wholesaler",
  "Auto body shop",
  "Auto chemistry shop",
  "Auto glass shop",
  "Auto machine shop",
  "Auto market",
  "Auto parts market",
  "Auto parts store",
  "Auto repair shop",
  "Auto spring shop",
  "Auto sunroof shop",
  "Baby store",
  "Bag shop",
  "Bagel shop",
  "Bait shop",
  "Baking supply store",
  "Balloon store",
  "Bangle Shop",
  "Banner store",
  "Battery store",
  "Battery wholesaler",
  "Bazar",
  "Beach entertainment shop",
  "Bead store",
  "Bead wholesaler",
  "Beauty products wholesaler",
  "Beauty supply store",
  "Bed shop",
  "Bedding store",
  "Beer garden",
  "Beer store",
  "Belt shop",
  "Bicycle repair shop",
  "Bicycle store",
  "Bicycle wholesaler",
  "Billiards supply store",
  "Bird shop",
  "Blinds shop",
  "Boat accessories supplier",
  "Boat repair shop",
  "Book store",
  "Books wholesaler",
  "Boot repair shop",
  "Boot store",
  "Boutique",
  "Bowling supply shop",
  "Brake shop",
  "Brewing supply store",
  "Bridal shop",
  "Bubble tea store",
  "Buddhist supplies store",
  "Burglar alarm store",
  "Butcher shop",
  "Butsudan store",
  "Cake decorating equipment shop",
  "Cake shop",
  "Call shop",
  "Camera repair shop",
  "Camera store",
  "Candle store",
  "Candy store",
  "Cane furniture store",
  "Cannabis store",
  "Canoe & kayak store",
  "Cattle market",
  "CD store",
  "Cell phone accessory store",
  "Cell phone store",
  "Ceramics wholesaler",
  "Cheese shop",
  "Chemical wholesaler",
  "Chicken shop",
  "Children's book store",
  "Children's furniture store",
  "Children's store",
  "Chinaware store",
  "Chinese medicine store",
  "Chinese supermarket",
  "Chocolate shop",
  "Cigar shop",
  "Coffee shop",
  "Coffee store",
  "Coffee wholesaler",
  "Cold cut store",
  "Collectibles store",
  "Comic book store",
  "Community garden",
  "Computer accessories store",
  "Computer desk store",
  "Computer software store",
  "Computer store",
  "Computer wholesaler",
  "Confectionery store",
  "Confectionery wholesaler",
  "Consignment shop",
  "Construction material wholesaler",
  "Convenience store",
  "Cookie shop",
  "Copy shop",
  "Copying supply store",
  "Cosmetics store",
  "Cosmetics wholesaler",
  "Costume jewelry shop",
  "Costume store",
  "Countertop store",
  "Craft store",
  "Cricket shop",
  "Cupcake shop",
  "Cured ham store",
  "Curtain store",
  "Custom confiscated goods store",
  "Custom t-shirt store",
  "Cutlery store",
  "Dairy store",
  "Dance store",
  "Dart supply store",
  "Jeans shop",
  "Dental supply store",
  "Department store",
  "Dessert shop",
  "Discount store",
  "Discount supermarket",
  "Dive shop",
  "DJ supply store",
  "Do-it-yourself shop",
  "Doll store",
  "Dollar store",
  "Donut shop",
  "Door shop",
  "Dress store",
  "Dried flower shop",
  "Dried seafood store",
  "Driveshaft shop",
  "Drone shop",
  "Drug store",
  "Drum store",
  "Dry fruit store",
  "Dry wall supply store",
  "Duty free store",
  "DVD store",
  "Dye store",
  "Eastern European grocery store",
  "Electric bicycle store",
  "Electric motor repair shop",
  "Electric motor store",
  "Electrical appliance wholesaler",
  "Electrical repair shop",
  "Electrical supply store",
  "Electrical products wholesaler",
  "Electronics accessories wholesaler",
  "Electronics hire shop",
  "Electronics repair shop",
  "Electronics store",
  "Electronics wholesaler",
  "Embroidery shop",
  "Equestrian store",
  "European grocery store",
  "Event ticket seller",
  "Fabric store",
  "Fabric wholesaler",
  "Fashion accessories store",
  "Animal feed store",
  "Felt boots store",
  "Fence supply store",
  "Feng shui shop",
  "Figurine shop",
  "Filipino grocery store",
  "Fireplace store",
  "Fireworks store",
  "Fish store",
  "Fishing store",
  "Exercise equipment store",
  "Fitness equipment wholesaler",
  "Flag store",
  "Flamenco dance store",
  "Flea market",
  "Floating market",
  "Flooring store",
  "Florist",
  "Flower market",
  "FMCG goods wholesaler",
  "Formal wear store",
  "Fresh food market",
  "Frozen food store",
  "Frozen yogurt shop",
  "Fruit and vegetable store",
  "Fruit and vegetable wholesaler",
  "Fruit wholesaler",
  "Fruits wholesaler",
  "Fur coat shop",
  "Furnace store",
  "Furniture accessories",
  "Furniture accessories supplier",
  "Furniture repair shop",
  "Furniture store",
  "Furniture wholesaler",
  "Futon store",
  "Game store",
  "Garden",
  "Garden center",
  "Garden furniture shop",
  "Garden machinery supplier",
  "Gardener",
  "Gas shop",
  "General store",
  "Electric generator shop",
  "Gift basket store",
  "Gift shop",
  "Gift wrap store",
  "Glass & mirror shop",
  "Glass merchant",
  "Glass shop",
  "Glassware store",
  "Glassware wholesaler",
  "Goldfish store",
  "Gourmet grocery store",
  "Government ration shop",
  "Greengrocer",
  "Grocery store",
  "Grow shop",
  "Guitar store",
  "Gun shop",
  "Haberdashery",
  "Ham shop",
  "Handbags shop",
  "Handicrafts wholesaler",
  "Hardware store",
  "Hat shop",
  "Hawaiian goods store",
  "Health and beauty shop",
  "Health food store",
  "Hearing aid store",
  "Hearing assistance earphone store",
  "Herb shop",
  "Herbal medicine store",
  "Hobby store",
  "Hookah store",
  "Hot tub store",
  "Hua gong shop",
  "Hua niao market place",
  "Hunting and fishing store",
  "Hunting store",
  "Hygiene articles wholesaler",
  "Hypermarket",
  "Ice cream shop",
  "Indian grocery store",
  "Indian sweets shop",
  "Industrial chemicals wholesaler",
  "Industrial supermarket",
  "Insulation materials store",
  "Internet marketing service",
  "Internet shop",
  "Irish goods store",
  "Italian grocery store",
  "Japanese cheap sweets shop",
  "Japanese confectionery shop",
  "Japanese grocery store",
  "Jewelry store",
  "Judaica store",
  "Juice shop",
  "Kebab shop",
  "Kilt shop and hire",
  "Kimono store",
  "Kiosk",
  "Kitchen furniture store",
  "Kitchen supply store",
  "Kite shop",
  "Knife store",
  "Knit shop",
  "Korean grocery store",
  "Kosher grocery store",
  "Landscaping supply store",
  "Leather coats store",
  "Leather goods store",
  "Leather goods wholesaler",
  "Leather wholesaler",
  "Lighting store",
  "Lighting products wholesaler",
  "Linens store",
  "Lingerie store",
  "Lingerie wholesaler",
  "Linoleum store",
  "Liquor store",
  "Lock Store",
  "Luggage store",
  "Luggage wholesaler",
  "Lumber store",
  "Machine shop",
  "Magazine store",
  "Magic store",
  "Map store",
  "Marine supply store",
  "Market",
  "Market researcher",
  "Masonry supply store",
  "Maternity store",
  "Mattress store",
  "Meat products store",
  "Meat wholesaler",
  "Medical book store",
  "Medical supply store",
  "Metal working shop",
  "Metaphysical supply store",
  "Mexican goods store",
  "Mexican grocery store",
  "Mineral water wholesaler",
  "Miniatures store",
  "Mirror shop",
  "Mobile phone repair shop",
  "Model train store",
  "Motor scooter repair shop",
  "Motorcycle parts store",
  "Motorcycle repair shop",
  "Motorcycle shop",
  "Movie rental kiosk",
  "Movie rental store",
  "Moving supply store",
  "Muffler shop",
  "Native american goods store",
  "Natural goods store",
  "Natural stone wholesaler",
  "Needlework shop",
  "Neon sign shop",
  "Newsstand",
  "Night market",
  "Noodle shop",
  "Notions store",
  "Novelties wholesaler",
  "Novelty store",
  "Nut store",
  "Office accessories wholesaler",
  "Office furniture store",
  "Office supply store",
  "Office supply wholesaler",
  "Optical wholesaler",
  "Organic drug store",
  "Organic food store",
  "Organic shop",
  "Oriental goods store",
  "Oriental medicine store",
  "Oriental rug store",
  "Orthopedic shoe store",
  "Orthopedic supplies store",
  "Outboard motor store",
  "Outdoor furniture store",
  "Outerwear store",
  "Outlet mall",
  "Outlet store",
  "Paan shop",
  "Packaging supply store",
  "Paint store",
  "Paintball store",
  "Paintings store",
  "Panipuri shop",
  "Paper store",
  "Party store",
  "Pasta shop",
  "Pastry shop",
  "Pawn shop",
  "Pen store",
  "Perfume store",
  "Pet store",
  "Pet supply store",
  "Pharmaceutical products wholesaler",
  "Photo shop",
  "Piano store",
  "Picture frame shop",
  "Pie shop",
  "Pine furniture shop",
  "Plast window store",
  "Plastic bags wholesaler",
  "Plastic products wholesaler",
  "Plumbing supply store",
  "Pond supply store",
  "Popcorn store",
  "Poster store",
  "Pottery store",
  "Poultry store",
  "Pretzel store",
  "Print shop",
  "Printer ink refill store",
  "Produce market",
  "Produce wholesaler",
  "Propeller shop",
  "Qing fang market place",
  "Quilt shop",
  "Radiator shop",
  "Raft trip outfitter",
  "Rare book store",
  "Record store",
  "Refrigerator store",
  "Religious book store",
  "Religious goods store",
  "Reptile store",
  "Rice cake shop",
  "Rice cracker shop",
  "Rice shop",
  "Rice wholesaler",
  "Rock shop",
  "Roofing supply store",
  "Rubber stamp store",
  "Rug store",
  "Running store",
  "Russian grocery store",
  "Rustic furniture store",
  "RV repair shop",
  "RV supply store",
  "Safe & vault shop",
  "Salad shop",
  "Sandwich shop",
  "Saree Shop",
  "Model shop",
  "Scooter repair shop",
  "Scrapbooking store",
  "Screen printing shop",
  "Screen printing supply store",
  "Screen store",
  "Seafood market",
  "Seafood wholesaler",
  "Seal shop",
  "Seasonal goods store",
  "Second hand store",
  "Sewing machine store",
  "Sewing shop",
  "Shelving store",
  "Shoe repair shop",
  "Shoe store",
  "Footwear wholesaler",
  "Shop supermarket furniture store",
  "Shopfitter",
  "Shopping mall",
  "Shower door shop",
  "Sign shop",
  "Silk store",
  "Skate shop",
  "Skateboard shop",
  "Ski shop",
  "Small appliance repair service",
  "Small claims assistance service",
  "Small engine repair service",
  "Smart shop",
  "Smoke shop",
  "Snowboard shop",
  "Soba noodle shop",
  "Sofa store",
  "Soup shop",
  "Souvenir store",
  "Spice store",
  "Spice wholesaler",
  "Stamp shop",
  "State liquor store",
  "Steamed bun shop",
  "Stereo rental store",
  "Store",
  "Store equipment supplier",
  "Store fixture supplier",
  "Sunglasses store",
  "Supermarket",
  "Surf shop",
  "Surgical products wholesaler",
  "Surgical supply store",
  "Surplus store",
  "Swimwear store",
  "T-shirt store",
  "Table tennis supply store",
  "Tack shop",
  "Tamale shop",
  "Tatami store",
  "Tattoo shop",
  "Tattoo supply store",
  "Tea market place",
  "Tea store",
  "Tea wholesaler",
  "Telemarketing service",
  "Telescope store",
  "Tennis store",
  "Threads and yarns wholesaler",
  "Thrift store",
  "Tile store",
  "Tire repair shop",
  "Tire shop",
  "Tobacco shop",
  "Tofu shop",
  "Toiletries store",
  "Tool & die shop",
  "Tool repair shop",
  "Tool store",
  "Tool wholesaler",
  "Tortilla shop",
  "Toy store",
  "Tractor parts store",
  "Tractor repair shop",
  "Traditional Kostume store",
  "Traditional market",
  "Trailer repair shop",
  "Trailer supply store",
  "Trophy shop",
  "Tropical fish store",
  "Truck accessories store",
  "Truck repair shop",
  "Tuxedo shop",
  "Underwear store",
  "Unfinished furniture store",
  "Uniform store",
  "Upholstery shop",
  "Used appliance store",
  "Used auto parts store",
  "Used bicycle shop",
  "Used book store",
  "Used CD store",
  "Used computer store",
  "Used furniture store",
  "Used game store",
  "Used office furniture store",
  "Used store fixture supplier",
  "Used tire shop",
  "Vacuum cleaner repair shop",
  "Vacuum cleaner store",
  "Vaporizer store",
  "Variety store",
  "Vegetable wholesale market",
  "Vegetable wholesaler",
  "Video game rental kiosk",
  "Video game rental store",
  "Video game store",
  "Video store",
  "Vinyl sign shop",
  "Violin shop",
  "Vitamin & supplements store",
  "Wallpaper store",
  "Washer & dryer store",
  "Watch store",
  "Water ski shop",
  "Waterbed store",
  "Wedding souvenir shop",
  "Wedding store",
  "Welding supply store",
  "Western apparel store",
  "Wheel store",
  "Wheelchair store",
  "Wholesale drugstore",
  "Wholesale florist",
  "Wholesale food store",
  "Wholesale grocer",
  "Wholesale market",
  "Wholesaler",
  "Wicker store",
  "Wig shop",
  "Window treatment store",
  "Windsurfing store",
  "Wine store",
  "Winemaking supply store",
  "Wood stove shop",
  "Woodworking supply store",
  "Wool store",
  "Yarn store",
  "Carport and pergola builder",
  "Car manufacturer",
  "Car repair and maintenance service",
  "Car security system installer",
  "Carpenter",
  "Carpet installer",
  "Carpet manufacturer",
  "Garage builder",
  "Mechanical contractor",
  "Cardiologist",
  "Cardiovascular and thoracic surgeon",
  "Emergency care physician",
  "Pediatric cardiologist",
  "Skin care clinic",
  "Car rental agency",
  "Child care agency",
  "Lawn care service",
  "Car inspection station",
  "Carabinieri police",
  "Car factory",
  "Mechanical plant",
  "Parking lot for motorcycles",
  "Home health care service",
  "Mobile home dealer",
  "Modular home dealer",
  "Car racing venue",
  "Carnival club",
  "Carpooling location",
  "Chess and card club",
  "Parking garage",
  "Powersports vehicle dealer",
  "Dump truck dealer",
  "Acura dealer",
  "Adult day care center",
  "Adult foster care service",
  "Air taxi",
  "Aircraft dealer",
  "Alfa Romeo dealer",
  "Art dealer",
  "Aston Martin dealer",
  "ATV dealer",
  "Audi dealer",
  "Auto bodywork mechanic",
  "Auto wrecker",
  "Bentley dealer",
  "BMW dealer",
  "BMW motorcycle dealer",
  "Boat dealer",
  "Boat trailer dealer",
  "Bugatti dealer",
  "Buick dealer",
  "Cadillac dealer",
  "Car alarm supplier",
  "Car dealer",
  "Car detailing service",
  "Car finance and loan company",
  "Car leasing service",
  "Car sharing location",
  "Car wash",
  "Career guidance service",
  "Carriage ride service",
  "Carvery",
  "Chevrolet dealer",
  "Child health care center",
  "Chrysler dealer",
  "Citroen dealer",
  "Coin dealer",
  "Construction machine dealer",
  "Crane dealer",
  "Cupra dealer",
  "Dacia dealer",
  "Daihatsu dealer",
  "Day care center",
  "Dealer of Fiat Professional",
  "Denture care center",
  "Department of motor vehicles",
  "Diamond dealer",
  "Diesel engine dealer",
  "Dodge dealer",
  "Dog day care center",
  "DS Automobiles dealer",
  "Ducati dealer",
  "Electric motor scooter dealer",
  "Electric motor vehicle dealer",
  "Electric motorcycle dealer",
  "Emergency care service",
  "Eye care center",
  "Family day care service",
  "Ferrari dealer",
  "Fiat dealer",
  "Foot care",
  "Ford dealer",
  "Forklift dealer",
  "Foster care service",
  "Garage door supplier",
  "Genesis dealer",
  "GMC dealer",
  "Gold dealer",
  "Harley-Davidson dealer",
  "Honda dealer",
  "Horse trailer dealer",
  "Hyundai dealer",
  "Indian Motorcycle dealer",
  "Infiniti dealer",
  "Iron ware dealer",
  "Isuzu dealer",
  "Jaguar dealer",
  "Jeep dealer",
  "Junk dealer",
  "Karma dealer",
  "Kawasaki motorcycle dealer",
  "Kia dealer",
  "Lamborghini dealer",
  "Lancia dealer",
  "Land Rover dealer",
  "Lexus dealer",
  "Lincoln dealer",
  "Livestock dealer",
  "Maserati dealer",
  "Maybach dealer",
  "Mazda dealer",
  "McLaren dealer",
  "Mechanic",
  "Mechanical engineer",
  "Mercedes-Benz dealer",
  "Metalware dealer",
  "MG dealer",
  "MINI dealer",
  "Minibus taxi service",
  "Mitsubishi dealer",
  "Model car play area",
  "Moped dealer",
  "Motor scooter dealer",
  "Motor vehicle dealer",
  "Motorcycle dealer",
  "Mountain cable car",
  "Nissan dealer",
  "Oldsmobile dealer",
  "Opel dealer",
  "Personal watercraft dealer",
  "Peugeot dealer",
  "Pontiac dealer",
  "Porsche dealer",
  "Pregnancy care center",
  "Race car dealer",
  "Ram dealer",
  "Renault dealer",
  "Rental car return location",
  "Rolls-Royce dealer",
  "RV dealer",
  "Saab dealer",
  "Salvage dealer",
  "Saturn dealer",
  "Scrap metal dealer",
  "Seat dealer",
  "Self service car wash",
  "Aged care",
  "Skin care products vending machine",
  "Skoda dealer",
  "Smart Car dealer",
  "Smart dealer",
  "Snowmobile dealer",
  "Stone carving",
  "Student career counseling office",
  "Suzuki dealer",
  "Suzuki motorcycle dealer",
  "Tata Motors dealer",
  "Taxi service",
  "Taxi stand",
  "Taxidermist",
  "Toner cartridge supplier",
  "Toyota dealer",
  "Tractor dealer",
  "Trailer dealer",
  "Triumph motorcycle dealer",
  "Truck dealer",
  "Urgent care center",
  "Used car dealer",
  "Used motorcycle dealer",
  "Used truck dealer",
  "Utility trailer dealer",
  "Volkswagen dealer",
  "Volvo dealer",
  "Yamaha motorcycle dealer",
  "Youth care service",
  "Lawn sprinkler system contractor",
  "Architectural and engineering model maker",
  "Building consultant",
  "Building inspector",
  "Musical instrument manufacturer",
  "Electric vehicle charging station contractor",
  "Stationery manufacturer",
  "Bathroom remodeler",
  "Clothes and fabric manufacturer",
  "Custom home builder",
  "Home builder",
  "Log home builder",
  "Modular home builder",
  "Sunroom contractor",
  "Makerspace",
  "Deck builder",
  "Portable building manufacturer",
  "Railroad contractor",
  "Sportwear manufacturer",
  "Agricultural machinery manufacturer",
  "Air conditioning contractor",
  "Aircraft maintenance company",
  "Aircraft manufacturer",
  "Alcohol manufacturer",
  "Aluminum welder",
  "Asphalt contractor",
  "Auto parts manufacturer",
  "Auto upholsterer",
  "Battery manufacturer",
  "Blacksmith",
  "Boat builders",
  "Boiler manufacturer",
  "Brick manufacturer",
  "Building designer",
  "Building equipment hire service",
  "Building firm",
  "Building materials supplier",
  "Building restoration service",
  "Building society",
  "Cement manufacturer",
  "Ceramic manufacturer",
  "Cheese manufacturer",
  "Chemical manufacturer",
  "Cider mill",
  "Clock and watch maker",
  "Computer hardware manufacturer",
  "Concrete contractor",
  "Contractor",
  "Coppersmith",
  "Cosmetic products manufacturer",
  "Cotton mill",
  "Countertop contractor",
  "Curtain supplier and maker",
  "Demolition contractor",
  "Display stand manufacturer",
  "Diving contractor",
  "Dock builder",
  "Door manufacturer",
  "Double glazing installer",
  "Dressmaker",
  "Drilling contractor",
  "Dry wall contractor",
  "Electrician",
  "Electronics manufacturer",
  "Elevator manufacturer",
  "Emergency locksmith service",
  "Engine rebuilding service",
  "Excavating contractor",
  "Fabric product manufacturer",
  "Feed manufacturer",
  "Fence contractor",
  "Fireplace manufacturer",
  "Flooring contractor",
  "Flour mill",
  "FMCG manufacturer",
  "Food manufacturer",
  "Food seasoning manufacturer",
  "Foreman builders association",
  "Fountain contractor",
  "Frozen food manufacturer",
  "Fur manufacturer",
  "Furniture maker",
  "Furniture manufacturer",
  "Gasket manufacturer",
  "Gazebo builder",
  "General contractor",
  "Glass manufacturer",
  "Glassware manufacturer",
  "Glazier",
  "Goldsmith",
  "Handyman/Handywoman/Handyperson",
  "Heating contractor",
  "Heritage building",
  "Horseshoe smith",
  "HVAC contractor",
  "Religious statue manufacturer",
  "Insulation contractor",
  "Interior construction contractor",
  "Interior fitting contractor",
  "Jewelry manufacturer",
  "Jute mill",
  "Kitchen remodeler",
  "Knife manufacturer",
  "Knitwear manufacturer",
  "Leather goods manufacturer",
  "Lighting contractor",
  "Lighting manufacturer",
  "Lingerie manufacturer",
  "Locksmith",
  "Logging contractor",
  "Machine maintenance service",
  "Machinery parts manufacturer",
  "Machining manufacturer",
  "Manufacturer",
  "Marble contractor",
  "Masonry contractor",
  "Match box manufacturer",
  "Mausoleum builder",
  "Medical equipment manufacturer",
  "Medical technology manufacturer",
  "Mill",
  "Mold maker",
  "Monument maker",
  "Olive oil manufacturer",
  "Optical products manufacturer",
  "Paint manufacturer",
  "Paper mill",
  "Paving contractor",
  "Piano maker",
  "Plasterer",
  "Plastic resin manufacturer",
  "Plumber",
  "Pond contractor",
  "Pottery manufacturer",
  "Property maintenance",
  "Railing contractor",
  "Remodeler",
  "Rice mill",
  "Roofing contractor",
  "RV repair and maintenance service",
  "Sailmaker",
  "Saw mill",
  "Shed builder",
  "Sheet metal contractor",
  "Shipbuilding and repair company",
  "Siding contractor",
  "Silversmith",
  "Skylight contractor",
  "Smart locker manufacturer",
  "Solar panel maintenance service",
  "Souvenir manufacturer",
  "Soy sauce maker",
  "Stair contractor",
  "Steel framework contractor",
  "Sticker manufacturer",
  "Stock exchange building",
  "Stringed instrument maker",
  "Stucco contractor",
  "Tea manufacturer",
  "Telecommunications contractor",
  "Textile mill",
  "Tile contractor",
  "Tile manufacturer",
  "Tyre manufacturer",
  "Tool manufacturer",
  "Toy manufacturer",
  "Trailer manufacturer",
  "Truss manufacturer",
  "Utility contractor",
  "Ventilating equipment manufacturer",
  "Wallpaper installer",
  "Watch manufacturer",
  "Water mill",
  "Weaving mill",
  "Welder",
  "Well drilling contractor",
  "Willow basket manufacturer",
  "Wind turbine builder",
  "Woodworker",
  "Plant nursery",
  "Wholesale plant nursery",
  "Dental implants periodontist",
  "Hair transplantation clinic",
  "Transplant surgeon",
  "Homeopathic pharmacy",
  "Sports massage therapist",
  "Massage therapist",
  "Thai massage therapist",
  "Sports medicine clinic",
  "Sports medicine physician",
  "Abortion clinic",
  "Acupuncture clinic",
  "Allergist",
  "Anesthesiologist",
  "Animal hospital",
  "Applied behavior analysis therapist",
  "Audiologist",
  "Ayurvedic clinic",
  "Biofeedback therapist",
  "Child psychiatrist",
  "Child psychologist",
  "Children Policlinic",
  "Children's hospital",
  "Chinese medicine clinic",
  "Chiropractor",
  "Cosmetic dentist",
  "Cosmetic surgeon",
  "Dental clinic",
  "Dentist",
  "Dermatologist",
  "Diabetologist",
  "Dietitian",
  "Doctor",
  "Ecologists association",
  "EMDR psychotherapist",
  "Endocrinologist",
  "Endodontist",
  "Endoscopist",
  "Family practice physician",
  "Fertility clinic",
  "Fertility physician",
  "Free clinic",
  "Gastroenterologist",
  "Gastrointestinal surgeon",
  "Gemologist",
  "General hospital",
  "Geriatrician",
  "Gestalt therapist",
  "Government hospital",
  "Obstetrician-gynecologist",
  "Gynecologist",
  "Hand surgeon",
  "Head and neck surgeon",
  "Heart hospital",
  "Hematologist",
  "Hepatologist",
  "Hospital",
  "Hospital equipment and supplies",
  "Hospital department",
  "Immunologist",
  "Infectious disease physician",
  "Internist",
  "Kinesiologist",
  "Kinesiotherapist",
  "Lasik surgeon",
  "Lymph drainage therapist",
  "Maternity hospital",
  "Medical clinic",
  "Men's health physician",
  "Mental health clinic",
  "Military hospital",
  "Neonatal physician",
  "Nephrologist",
  "Neurologist",
  "Neurophysiologist",
  "Neuropsychologist",
  "Neurosurgeon",
  "Numerologist",
  "Nurse practitioner",
  "Nutritionist",
  "Women's health clinic",
  "Occupational medical physician",
  "Occupational therapist",
  "Oncologist",
  "Ophthalmologist",
  "Ophthalmology clinic",
  "Optician",
  "Optometrist",
  "Oral and maxillofacial surgeon",
  "Oral surgeon",
  "Oriental medicine clinic",
  "Orthodontist",
  "Orthopedic clinic",
  "Orthopedic surgeon",
  "Orthoptist",
  "Osteopath",
  "Otolaryngologist",
  "Otolaryngology clinic",
  "Pain control clinic",
  "Pain management physician",
  "Pathologist",
  "Pediatric clinic",
  "Pediatric dentist",
  "Pediatric dermatologist",
  "Pediatric endocrinologist",
  "Pediatric gastroenterologist",
  "Pediatric hematologist",
  "Pediatric nephrologist",
  "Pediatric neurologist",
  "Pediatric oncologist",
  "Pediatric ophthalmologist",
  "Pediatric orthopedic surgeon",
  "Pediatric pulmonologist",
  "Pediatric rheumatologist",
  "Pediatric surgeon",
  "Pediatric urologist",
  "Pediatrician",
  "Pedorthist",
  "Periodontist",
  "Permanent make-up clinic",
  "Pharmacy",
  "Physiatrist",
  "Physician assistant",
  "Physician referral service",
  "Physical therapist",
  "Physical therapy clinic",
  "Plastic surgeon",
  "Plastic surgery clinic",
  "Podiatrist",
  "Private hospital",
  "Proctologist",
  "Prosthodontist",
  "Psychiatric hospital",
  "Psychiatrist",
  "Psychoanalyst",
  "Psychologist",
  "Psychomotor therapist",
  "Psychoneurological specialized clinic",
  "Psychopedagogy clinic",
  "Psychosocial therapist",
  "Psychotherapist",
  "Pulmonologist",
  "Radiologist",
  "Radiotherapist",
  "Reflexologist",
  "Registered general nurse",
  "Reiki therapist",
  "Reproductive health clinic",
  "Rheumatologist",
  "Sexologist",
  "Sleep clinic",
  "Specialized clinic",
  "Specialized hospital",
  "Speech pathologist",
  "STD clinic",
  "Surgeon",
  "Surgical oncologist",
  "TB clinic",
  "Travel clinic",
  "Urologist",
  "Urology clinic",
  "Vascular surgeon",
  "Venereologist",
  "Veterans hospital",
  "Veterinary pharmacy",
  "Walk-in clinic",
  "Labor relations attorney",
  "Music instructor",
  "Rock climbing instructor",
  "Labor union",
  "Aero dance class",
  "Apprenticeship center",
  "Aromatherapy class",
  "Assistante maternelle",
  "Biochemistry lab",
  "Boating instructor",
  "Body shaping class",
  "Calligraphy lesson",
  "Chemistry lab",
  "Chess instructor",
  "Childbirth class",
  "Chinese language instructor",
  "Civil examinations academy",
  "Cooking class",
  "Custom label printer",
  "Dental laboratory",
  "Drawing lessons",
  "Emergency training",
  "Gambling instructor",
  "Guitar instructor",
  "Hip hop dance class",
  "Ice skating instructor",
  "Japanese language instructor",
  "Kindergarten",
  "Knitting instructor",
  "Laboratory",
  "Laboratory equipment supplier",
  "Learner driver training area",
  "Lyceum",
  "Medical laboratory",
  "Meditation instructor",
  "Mehandi class",
  "Mountaineering class",
  "Painting lessons",
  "Pharmaceutical lab",
  "Photo lab",
  "Photography class",
  "Piano instructor",
  "Pottery classes",
  "Private tutor",
  "Religious institution",
  "Salsa classes",
  "SCUBA instructor",
  "Seminary",
  "Shogi lesson",
  "Skating instructor",
  "Special educator",
  "Stitching class",
  "Tennis instructor",
  "Training center",
  "Tutoring service",
  "Vocal instructor",
  "Waldorf kindergarten",
  "Water skiing instructor",
  "Wood working class",
  "X-ray lab",
  "Yeshiva",
  "Yoga instructor",
  "Criminal justice attorney",
  "Power plant consultant",
  "House sitter agency",
  "Commercial real estate agency",
  "Commercial real estate inspector",
  "Estate litigation attorney",
  "Estate planning attorney",
  "Home help service agency",
  "Home inspector",
  "Home insurance agency",
  "Industrial real estate agency",
  "Mobile home rental agency",
  "Real estate agency",
  "Real estate agent",
  "Real estate attorney",
  "Real estate consultant",
  "Real estate developer",
  "Real estate rental agency",
  "Real estate surveyor",
  "Vacation home rental agency",
  "Lawn bowls club",
  "Office space rental agency",
  "Retail space rental agency",
  "Airline ticket agency",
  "Credit reporting agency",
  "Passport agent",
  "Accountant",
  "Acoustical consultant",
  "Administrative attorney",
  "Adoption agency",
  "Advertising agency",
  "Architect",
  "Architects association",
  "Architectural designer",
  "Architecture firm",
  "Attorney referral service",
  "Audio visual consultant",
  "Auditor",
  "Auto broker",
  "Auto insurance agency",
  "Auto tag agency",
  "Aviation consultant",
  "Bank",
  "Bankruptcy attorney",
  "Bankruptcy service",
  "Betting agency",
  "Blood bank",
  "BPO placement agency",
  "Branding agency",
  "Bus charter",
  "Bus ticket agency",
  "Business attorney",
  "Business banking service",
  "Business broker",
  "Business management consultant",
  "Central bank",
  "Certification agency",
  "Chartered accountant",
  "Civil law attorney",
  "Commercial agent",
  "Computer consultant",
  "Condominium rental agency",
  "Consultant",
  "Cooperative bank",
  "Crane rental agency",
  "Cruise agency",
  "Customs broker",
  "Customs consultant",
  "Debt collection agency",
  "Dental insurance agency",
  "Design agency",
  "District attorney",
  "Divorce lawyer",
  "E commerce agency",
  "Economic consultant",
  "Economic development agency",
  "Elder law attorney",
  "Employment agency",
  "Employment attorney",
  "Employment consultant",
  "Energy advisory service",
  "Engineering consultant",
  "Entertainment agency",
  "Environmental attorney",
  "Environmental consultant",
  "Equipment rental agency",
  "Executive suite rental agency",
  "Executor",
  "Family law attorney",
  "Federal Agency for Technical Relief",
  "Feng shui consultant",
  "Finance broker",
  "Financial advisor",
  "Financial consultant",
  "Fire protection consultant",
  "Fishing charter",
  "Food and beverage consultant",
  "Food bank",
  "Food broker",
  "Foreign trade consultant",
  "Forensic consultant",
  "Funeral director",
  "General practice attorney",
  "Health consultant",
  "Health insurance agency",
  "Helicopter charter",
  "Human resource consulting",
  "Image consultant",
  "Immigration attorney",
  "Income protection insurance agency",
  "Industrial consultant",
  "Insurance agency",
  "Insurance agent",
  "Insurance attorney",
  "Insurance broker",
  "Interior architect office",
  "International trade consultant",
  "Investment bank",
  "Judicial scrivener",
  "Land surveyor",
  "Landscape architect",
  "Law firm",
  "Law library",
  "Lawn equipment rental service",
  "Lawn irrigation equipment supplier",
  "Lawn mower repair service",
  "Lawyer",
  "Lawyers association",
  "Life insurance agency",
  "Lighting consultant",
  "Loan agency",
  "Loss adjuster",
  "Marine surveyor",
  "Media consultant",
  "Medical examiner",
  "Medical lawyer",
  "Mining consultant",
  "Mobile money agent",
  "Mortgage broker",
  "Mortgage lender",
  "Motorcycle insurance agency",
  "Motorcycle rental agency",
  "Nursing agency",
  "Organ donation and tissue bank",
  "Patent attorney",
  "Personal injury attorney",
  "Photo agency",
  "Press advisory",
  "Private sector bank",
  "Probate attorney",
  "Quantity surveyor",
  "Recruiter",
  "Renter's insurance agency",
  "Recreational vehicle rental agency",
  "Savings bank",
  "Social security attorney",
  "Sperm bank",
  "Stock broker",
  "Superannuation consultant",
  "Surveyor",
  "Talent agency",
  "Tax assessor",
  "Tax attorney",
  "Tax consultant",
  "Temp agency",
  "Timeshare agency",
  "Train ticket agency",
  "Travel agency",
  "Trial attorney",
  "Truck rental agency",
  "Trust bank",
  "Van rental agency",
  "Vastu consultant",
  "Vehicle shipping agent",
  "Visa consulting service",
  "Yacht broker",
  "Television station",
  "Museum of zoology",
  "Theater production",
  "Live music venue",
  "Museum of space history",
  "Musical club",
  "Rock music club",
  "Model portfolio studio",
  "Portrait studio",
  "Aboriginal art gallery",
  "Amateur theater",
  "Amphitheater",
  "Animation studio",
  "Archaeological museum",
  "Army museum",
  "Art gallery",
  "Art museum",
  "Art studio",
  "Artist",
  "Ballet theater",
  "Balloon artist",
  "Band",
  "Children's museum",
  "Children's theater",
  "Circus",
  "Closed circuit television",
  "Drive-in movie theater",
  "Entertainer",
  "Ethnographic museum",
  "Flamenco theater",
  "Handicraft museum",
  "Heritage museum",
  "Historical place museum",
  "History museum",
  "IMAX theater",
  "Karaoke",
  "Karaoke equipment rental service",
  "Local history museum",
  "Magician",
  "Make-up artist",
  "Maritime museum",
  "Modern art museum",
  "Movie studio",
  "Movie theater",
  "Museum",
  "Music management and promotion",
  "Music producer",
  "Musical instrument rental service",
  "Musician",
  "Musician and composer",
  "National museum",
  "Natural history museum",
  "Open air museum",
  "Orchestra",
  "Outdoor movie theater",
  "Painting studio",
  "Performing arts theater",
  "Photography studio",
  "Puppet theater",
  "Radio broadcaster",
  "Rail museum",
  "Recording studio",
  "Rehearsal studio",
  "Science museum",
  "Sculptor",
  "Sculpture",
  "Sculpture museum",
  "Stage",
  "Stage lighting equipment supplier",
  "Stained glass studio",
  "Tattoo artist",
  "Technology museum",
  "Television repair service",
  "Theater company",
  "Toy museum",
  "Video arcade",
  "Video karaoke",
  "War museum",
  "Wax museum",
  "Rugby league club",
  "Skatepark",
  "Aerated drinks supplier",
  "Catering food and drink supplier",
  "Drinking water fountain",
  "Drinking water supplier",
  "Freestyle wrestling",
  "Indoor snowcenter",
  "Natural rock climbing area",
  "Playgroup",
  "Recycling center",
  "Recycling drop-off location",
  "Road cycling",
  "Rock climbing",
  "Roller coaster",
  "Rugby",
  "Velodrome",
  "Christmas tree farm",
  "Congregation",
  "Hindu priest",
  "Parish",
  "Priest",
  "Gurudwara",
  "City courthouse",
  "Housing authority",
  "Police officers' housing",
  "Alternative fuel station",
  "Border crossing station",
  "Cell phone charging station",
  "Compressed natural gas station",
  "Coast guard station",
  "Court reporter",
  "Electric vehicle charging station",
  "Electrical substation",
  "Fire station",
  "First aid station",
  "Gas station",
  "Port authority",
  "Power station",
  "Self service health station",
  "Smog inspection station",
  "Toll station",
  "Waste transfer station",
  "Weigh station",
  "Civil police",
  "Company registry",
  "Council",
  "Court executive officer",
  "Credit union",
  "District Justice",
  "Embassy",
  "Federal credit union",
  "Federal police",
  "Food court",
  "Guardia Di Finanza Police",
  "Intellectual property registry",
  "Justice department",
  "Land planning authority",
  "Land registry office",
  "Regional council",
  "Registry office",
  "State parliament",
  "State police",
  "Student union",
  "Tenant's union",
  "Oilfield",
  "Vineyard",
  "Greenhouse",
  "Land allotment",
  "Aquaculture farm",
  "Arboretum",
  "Botanica",
  "Cattle farm",
  "Chamber of agriculture",
  "Children's farm",
  "Coalfield",
  "Dairy farm",
  "Dairy farm equipment supplier",
  "Farm",
  "Farm bureau",
  "Farm equipment repair service",
  "Farm equipment supplier",
  "Fish farm",
  "Forestry service",
  "Honey farm",
  "Horsestable studfarm",
  "National forest",
  "Oil field equipment supplier",
  "Orchid farm",
  "Organic farm",
  "Pick your own farm produce",
  "Pig farm",
  "Poultry farm",
  "Seafood farm",
  "Shrimp farm",
  "State owned farm",
  "Tree farm",
  "Truck farmer",
  "Wind farm",
  "Zoo",
  "Passport photo processor",
  "Agricultural production",
  "Artificial plant supplier",
  "Asphalt mixing plant",
  "Bonsai plant supplier",
  "Cannery",
  "Chemical plant",
  "Chocolate factory",
  "Concrete factory",
  "Cooling plant",
  "Dental implants provider",
  "Desalination plant",
  "Factory equipment supplier",
  "Film production company",
  "Filtration plant",
  "Fish processing",
  "Food processing company",
  "Food processing equipment",
  "Foundry",
  "Fruit and vegetable processing",
  "Gravel plant",
  "Hydroelectric power plant",
  "Incineration plant",
  "Interior plant service",
  "Meat processor",
  "Metal processing company",
  "Nuclear power plant",
  "Oil refinery",
  "Plant and machinery hire",
  "Power plant equipment supplier",
  "Sand plant",
  "Sewage treatment plant",
  "Shoe factory",
  "Solar photovoltaic power plant",
  "Stainless steel plant",
  "Sugar factory",
  "Tannery",
  "Thermal power plant",
  "Video production service",
  "Water treatment plant",
  "Warehouse club",
  "Fairground",
  "Free parking lot",
  "Marksmen's clubhouse",
  "Mobile home park",
  "Parking lot",
  "Parking lot for bicycles",
  "Tsukigime parking lot",
  "Manufactured home transporter",
  "House sitter",
  "Cured ham warehouse",
  "Customs warehouse",
  "Door warehouse",
  "Junkyard",
  "Salvage yard",
  "Shipyard",
  "Train yard",
  "Warehouse",
  "Auction house",
  "Boarding house",
  "Bonesetting house",
  "Children's home",
  "Chinese tea house",
  "Clothing alteration service",
  "Clothing supplier",
  "Commissioner for Oaths",
  "Cottage",
  "Cottage rental",
  "Country house",
  "Crab house",
  "Department of housing",
  "Display home center",
  "Emergency room",
  "Escape room center",
  "Estate appraiser",
  "Estate liquidator",
  "Favela",
  "Funeral home",
  "Gambling house",
  "Ghost town",
  "Ground self defense force",
  "Group home",
  "Guest house",
  "Halfway house",
  "Haunted house",
  "Haute couture fashion house",
  "Holiday home",
  "Home automation company",
  "Home cinema installation",
  "Home help",
  "Home staging service",
  "Homekill service",
  "Homeless service",
  "Homeless shelter",
  "Homeopath",
  "Homeowners' association",
  "House cleaning service",
  "House clearance service",
  "Houseboat rental service",
  "Household chemicals supplier",
  "Housing association",
  "Housing complex",
  "Housing cooperative",
  "Housing development",
  "Housing society",
  "Housing utility company",
  "Livestock auction house",
  "Low income housing program",
  "Mahjong house",
  "Manor house",
  "Media house",
  "Memorial estate",
  "Military town",
  "Mission",
  "Non smoking holiday home",
  "Nursing home",
  "Opera house",
  "Pedestrian zone",
  "Pet groomer",
  "Picnic ground",
  "Protective clothing supplier",
  "Real estate appraiser",
  "Real estate auctioneer",
  "Retirement home",
  "Road safety town",
  "Roommate referral service",
  "Scout home",
  "Sheltered housing",
  "Slaughterhouse",
  "Steak house",
  "Student housing center",
  "Tea house",
  "Teachers' housing",
  "Toolroom",
  "Townhouse complex",
  "Sports club",
  "Adult entertainment club",
  "Aeroclub",
  "Aerospace company",
  "Aikido club",
  "Amusement park",
  "Amusement park ride",
  "Anime club",
  "Badminton club",
  "Beach club",
  "Bicycle club",
  "Blues club",
  "BMX venue",
  "Board game club",
  "Boat club",
  "Bowling club",
  "Bridge club",
  "Business park",
  "Cannabis club",
  "Canoe and kayak club",
  "Chess club",
  "Children's club",
  "City park",
  "Club",
  "Comedy club",
  "Computer club",
  "Conservative club",
  "Country club",
  "Country park",
  "Coworking space",
  "Croquet club",
  "Curling club",
  "Dance club",
  "Day spa",
  "Day-use onsen",
  "Disco club",
  "Dive club",
  "Dog park",
  "Ecological park",
  "Equestrian club",
  "Erotic massage",
  "Facial spa",
  "Festival",
  "Fish spa",
  "Fishing club",
  "Foot massage parlor",
  "Gay night club",
  "Gay sauna",
  "Go club",
  "Go-karting venue",
  "Gun club",
  "Hammam",
  "Handball club",
  "Handicraft fair",
  "Health spa",
  "Hiking club",
  "Host club",
  "Hot bedstone spa",
  "Hunting club",
  "Jazz club",
  "Judo club",
  "Kabaddi club",
  "Karate club",
  "Leagues club",
  "Legal affairs bureau",
  "Little league club",
  "Lounge",
  "Massage spa",
  "Medical spa",
  "Memorial park",
  "Motoring club",
  "National park",
  "Netball club",
  "Newspaper distribution service",
  "Night club",
  "Nudist club",
  "Nudist park",
  "Off-road racing venue",
  "Onsen",
  "Oxygen cocktail spot",
  "Padel club",
  "Park",
  "Park & ride",
  "Parkour spot",
  "Polo club",
  "Pony club",
  "Pool cleaning service",
  "Racquetball club",
  "Rowing club",
  "Rsl club",
  "RV park",
  "Sailing club",
  "Sauna",
  "Sauna club",
  "Scale model club",
  "Scenic spot",
  "Ski club",
  "Skittle club",
  "Social club",
  "Spa",
  "Spa and health club",
  "Space of remembrance",
  "Squash club",
  "Stamp collectors club",
  "State park",
  "Surf lifesaving club",
  "Swim club",
  "Technology park",
  "Theme park",
  "Trade fair construction company",
  "Traditional costume club",
  "Travel lounge",
  "Valet parking service",
  "Veterans affairs department",
  "Water park",
  "Wi-Fi spot",
  "Wildlife and safari park",
  "Wildlife park",
  "Wine club",
  "Workers' club",
  "Yacht club",
  "Youth club",
  "Adventure sports center",
  "Aerial sports center",
  "Airline",
  "Airplane",
  "Airport",
  "Airport shuttle service",
  "Airstrip",
  "Boat ramp",
  "Chemical exporter",
  "City department of transportation",
  "Coal exporter",
  "Computer support and services",
  "Container terminal",
  "Copier repair service",
  "Cotton exporter",
  "Cruise terminal",
  "Department of Transportation",
  "Disability services and support organization",
  "Adaptive sports center",
  "Domestic airport",
  "Ear piercing service",
  "Equipment exporter",
  "Equipment importer",
  "Exporter",
  "Fishing pier",
  "Food and beverage exporter",
  "Garment exporter",
  "Handicapped transportation service",
  "Handicraft exporter",
  "Heliport",
  "Heritage railroad",
  "Horse transport supplier",
  "Import export company",
  "Importer",
  "International airport",
  "Jewelry exporter",
  "Jute exporter",
  "Leather exporter",
  "Medicine exporter",
  "Natural stone exporter",
  "Observation deck",
  "Paper exporter",
  "Passport office",
  "Patients support association",
  "Payment terminal",
  "Port operating company",
  "Portable toilet supplier",
  "POS terminal supplier",
  "Railroad company",
  "Railroad equipment supplier",
  "Railroad ties supplier",
  "Refrigerated transport service",
  "Regional airport",
  "River port",
  "Roads ports and canals engineers association",
  "Spice exporter",
  "Sports equipment rental service",
  "Students support association",
  "Support group",
  "Tea exporter",
  "Textile exporter",
  "Communications tower",
  "Transportation escort service",
  "Transportation service",
  "Vehicle exporter",
  "Visa and passport office",
  "Water sports equipment rental service",
  "Childminder",
  "Dog walker",
  "Doula",
  "Midwife",
  "Pet sitter",
  "Dumpster rental service",
  "Garbage dump",
  "Aadhaar center",
  "Aboriginal and Torres Strait Islander organisation",
  "Abrasives supplier",
  "Accounting firm",
  "Acupuncturist",
  "Addiction treatment center",
  "Commercial photographer",
  "Antenna service",
  "Aerial photographer",
  "Aeronautical engineer",
  "Agenzia Entrate",
  "Aggregate supplier",
  "Agistment service",
  "Agricultural association",
  "Agricultural cooperative",
  "Agricultural engineer",
  "Agricultural organization",
  "Agricultural service",
  "Agrochemicals supplier",
  "Air ambulance service",
  "Air compressor repair service",
  "Air compressor supplier",
  "Air conditioning repair service",
  "Air conditioning system supplier",
  "Air duct cleaning service",
  "Air filter supplier",
  "Air force base",
  "Airbrushing service",
  "Aircraft rental service",
  "Alcohol retail monopoly",
  "Alcoholism treatment program",
  "Alternative medicine practitioner",
  "Alternator supplier",
  "Aluminum supplier",
  "Aluminum frames supplier",
  "Aluminum window",
  "Ambulance service",
  "Ammunition supplier",
  "Amusement center",
  "Amusement machine supplier",
  "Amusement ride supplier",
  "Anganwadi center",
  "Animal control service",
  "Animal protection organization",
  "Animal rescue service",
  "Animal shelter",
  "Animal watering hole",
  "Anodizing service",
  "Antique furniture restoration service",
  "Appliance parts supplier",
  "Appliance rental service",
  "Appliance repair service",
  "Appraiser",
  "Aquarium",
  "Aquatic center",
  "Arborist service",
  "Archery range",
  "Archive",
  "Armed forces association",
  "Army facility",
  "Aromatherapy service",
  "Art center",
  "Art restoration service",
  "Arts organization",
  "Asbestos testing service",
  "Assisted living facility",
  "Association / Organization",
  "Astrologer",
  "Asylum center",
  "ATM",
  "ATV rental service",
  "Audiovisual equipment rental service",
  "Audio visual equipment repair service",
  "Audio visual equipment supplier",
  "Auto air conditioning service",
  "Auto auction",
  "Auto body parts supplier",
  "Auto dent removal service",
  "Auto electrical service",
  "Auto glass repair service",
  "Auto painting",
  "Auto radiator repair service",
  "Auto restoration service",
  "Auto rickshaw stand",
  "Auto tune up service",
  "Auto window tinting service",
  "Automation company",
  "Automobile storage facility",
  "Awning supplier",
  "Bail bonds service",
  "Basket supplier",
  "Batting cage center",
  "Beach cleaning service",
  "Beach pavillion",
  "Bearing supplier",
  "Beautician",
  "Beauty product supplier",
  "Beauty products vending machine",
  "Beauty salon",
  "Bee relocation service",
  "Beer distributor",
  "Beverage distributor",
  "Bicycle rack",
  "Bicycle rental service",
  "Bike wash",
  "Biotechnology company",
  "Bird control service",
  "Bird watching area",
  "Birth center",
  "Birth certificate service",
  "Birth control center",
  "Blood donation center",
  "Blood testing service",
  "Blueprint service",
  "Boat cleaning service",
  "Boat cover supplier",
  "Boat detailing service",
  "Boat rental service",
  "Boat storage facility",
  "Boiler supplier",
  "Bookbinder",
  "Bookkeeping service",
  "Border guard",
  "Bottle & can redemption center",
  "Bottled water supplier",
  "Bouncy castle hire",
  "Bowling alley",
  "Box lunch supplier",
  "BPO company",
  "Bricklayer",
  "Bridge",
  "Bullring",
  "Bungee jumping center",
  "Bus company",
  "Bus depot",
  "Business administration service",
  "Business center",
  "Business development service",
  "Business networking company",
  "Business to business service",
  "Butane gas supplier",
  "Cable company",
  "Call center",
  "Cancer treatment center",
  "Canoe & kayak rental service",
  "Canoeing area",
  "Chauffeur service",
  "Casino",
  "Casket service",
  "Castle",
  "Cat boarding service",
  "Cat breeder",
  "Cat trainer",
  "Catering equipment rental service",
  "Caterer",
  "Cattery",
  "Ceiling supplier",
  "Cement supplier",
  "Cemetery",
  "Chamber of Commerce",
  "Chamber of handicrafts",
  "Charity",
  "Check cashing service",
  "Chemical engineering service",
  "Faculty of chemistry",
  "Children's amusement center",
  "Children's library",
  "Children's party service",
  "Chimney services",
  "Chimney sweep",
  "Chocolate artisan",
  "Choir",
  "Cinema equipment supplier",
  "Citizen information bureau",
  "City clerk's office",
  "City district office",
  "City employment department",
  "City government office",
  "City tax office",
  "Civil defense",
  "Civil engineer",
  "Civil engineering company",
  "Cleaning products supplier",
  "Clock repair service",
  "CNG fitment center",
  "Coaching center",
  "Coal supplier",
  "Coffee machine supplier",
  "Coffee roasters",
  "Coffee stand",
  "Coffee vending machine",
  "Coffin supplier",
  "Coin operated laundry equipment supplier",
  "Coin operated locker",
  "Cold storage facility",
  "Commercial printer",
  "Commercial refrigerator supplier",
  "Community health center",
  "Computer networking service",
  "Computer repair service",
  "Computer security service",
  "Computer service",
  "Concrete metal framework supplier",
  "Concrete product supplier",
  "Condiments supplier",
  "Condominium complex",
  "Construction company",
  "Construction equipment supplier",
  "Construction machine rental service",
  "Consumer advice center",
  "Contact lenses supplier",
  "Container service",
  "Container supplier",
  "Containers supplier",
  "Conveyancer",
  "Copper supplier",
  "Copywriting service",
  "Corporate gift supplier",
  "Corporate office",
  "Cosmetics industry",
  "Cost accounting service",
  "Costume rental service",
  "Cotton supplier",
  "Counselor",
  "County government office",
  "Courier service",
  "Crane service",
  "Craniosacral therapy",
  "Credit counseling service",
  "Cremation service",
  "Crime victim service",
  "Crop grower",
  "Cruise line company",
  "Crushed stone supplier",
  "Crypto ATM",
  "Cultural association",
  "Cultural landmark",
  "Currency exchange service",
  "Custom tailor",
  "Customs office",
  "Cycle rickshaw stand",
  "Dairy",
  "Dairy supplier",
  "Dance company",
  "Dance pavillion",
  "Data center",
  "Data entry service",
  "Data recovery service",
  "Database management company",
  "Dating service",
  "Deaf service",
  "Debris removal service",
  "Debt collecting",
  "Decal supplier",
  "Dental hygienist",
  "Dental radiology",
  "Department of Social Services",
  "Design engineer",
  "Detention center",
  "Diabetes center",
  "Diabetes equipment supplier",
  "Diagnostic center",
  "Dialysis center",
  "Diamond buyer",
  "Diaper service",
  "Diesel engine repair service",
  "Diesel fuel supplier",
  "Digital printer",
  "Digital printing service",
  "Direct mail advertising",
  "Dirt supplier",
  "Disability equipment supplier",
  "Disposable tableware supplier",
  "Distance learning center",
  "Distillery",
  "Distribution service",
  "District government office",
  "District office",
  "Diving center",
  "Divorce service",
  "DJ service",
  "Dog breeder",
  "Dog trainer",
  "Dogsled ride service",
  "Doll restoration service",
  "Domestic abuse treatment center",
  "Donations center",
  "Door supplier",
  "Drafting equipment supplier",
  "Drafting service",
  "Drainage service",
  "Dress and tuxedo rental service",
  "Drilling equipment supplier",
  "Driver's license office",
  "Driving test center",
  "Drone service",
  "Drug testing service",
  "Dry cleaner",
  "Dry ice supplier",
  "Dryer vent cleaning service",
  "Dude ranch",
  "Dyeworks",
  "Dynamometer supplier",
  "E-commerce service",
  "Earth works company",
  "Eating disorder treatment center",
  "EFTPOS equipment supplier",
  "Egg supplier",
  "Electric utility company",
  "Electrical engineer",
  "Electrical equipment supplier",
  "Electrical installation service",
  "Electrolysis hair removal service",
  "Electronic engineering service",
  "Electronic parts supplier",
  "Electronics company",
  "Electronics engineer",
  "Electronics vending machine",
  "Elevator service",
  "Embossing service",
  "Embroidery service",
  "Emergency call booth",
  "Emergency dental service",
  "Emergency veterinarian service",
  "Employment center",
  "Energy equipment and solutions",
  "Energy supplier",
  "Engineer",
  "Engraver",
  "Envelope supplier",
  "Environment office",
  "Environment renewable natural resources",
  "Environmental engineer",
  "Environmental health service",
  "Environmental organization",
  "Environmental protection organization",
  "Equestrian facility",
  "Equipment supplier",
  "Escrow service",
  "Esthetics service",
  "Event management company",
  "Event planner",
  "Event technology service",
  "Executive search firm",
  "Exhibit",
  "Exhibition and trade center",
  "Exhibition planner",
  "Eyelash salon",
  "Fabrication engineer",
  "Family counselor",
  "Family planning center",
  "Family planning counselor",
  "Family service center",
  "Farrier service",
  "Fashion designer",
  "Fastener supplier",
  "Fax service",
  "Federal government office",
  "Fencing salon",
  "Ferris wheel",
  "Ferry service",
  "Fertilizer supplier",
  "Fiber optic products supplier",
  "Fiberglass repair service",
  "Fiberglass supplier",
  "Film and photograph library",
  "Financial audit",
  "Financial planner",
  "Fingerprinting service",
  "Finishing materials supplier",
  "Fire alarm supplier",
  "Fire damage restoration service",
  "Fire department equipment supplier",
  "Fire protection equipment supplier",
  "Fire protection service",
  "Fire protection system supplier",
  "Firewood supplier",
  "Fireworks supplier",
  "Fishing pond",
  "Fitted furniture supplier",
  "Fixed-base operator",
  "Flavours fragrances and aroma supplier",
  "Floor refinishing service",
  "Floor sanding and polishing service",
  "Flower designer",
  "Foam rubber producer",
  "Foam rubber supplier",
  "Food machinery supplier",
  "Food manufacturing supply",
  "Food producer",
  "Food products supplier",
  "Foot bath",
  "Foreclosure service",
  "Foreign consulate",
  "Foreign exchange students organization",
  "Forklift rental service",
  "Fortress",
  "Fortune telling services",
  "Foundation",
  "Fraternal organization",
  "Freight forwarding service",
  "Frozen dessert supplier",
  "Fruit parlor",
  "Fuel supplier",
  "Full dress rental service",
  "Funeral celebrant service",
  "Fur service",
  "Furnace parts supplier",
  "Furnace repair service",
  "Furniture rental service",
  "Garbage collection service",
  "Gas company",
  "Gas cylinders supplier",
  "Gas engineer",
  "Gas installation service",
  "Gas logs supplier",
  "Gasfitter",
  "Gated community",
  "Gay & lesbian organization",
  "Genealogist",
  "General practitioner",
  "Faculty of geography and history",
  "Geological research company",
  "Geological service",
  "Geotechnical engineer",
  "Glass block supplier",
  "Glass blower",
  "Glass cutting service",
  "Glass engraving service",
  "Glass etching service",
  "Glass industry",
  "Glass repair service",
  "Glasses repair service",
  "Gold mining company",
  "Government economic program",
  "Government office",
  "GPS supplier",
  "Grain elevator",
  "Granite supplier",
  "Graphic designer",
  "Gravel pit",
  "Green energy supplier",
  "Guardia Civil",
  "Gypsum product supplier",
  "Hair extension technician",
  "Hair extensions supplier",
  "Hair removal service",
  "Hair replacement service",
  "Hair salon",
  "Handicraft",
  "Hang gliding center",
  "Hawker center",
  "Hawker stall",
  "Hay supplier",
  "Head start center",
  "Health counselor",
  "Hearing aid repair service",
  "Heating equipment supplier",
  "Heating oil supplier",
  "Height works",
  "Helium gas supplier",
  "Herbalist",
  "Heritage preservation",
  "High ropes course",
  "Highway patrol",
  "Hiking area",
  "Hiking guide",
  "Historical landmark",
  "Historical society",
  "HIV testing center",
  "Holding company",
  "Holistic medicine practitioner",
  "Horse boarding stable",
  "Horse breeder",
  "Horse rental service",
  "Horse trainer",
  "Horseback riding service",
  "Hose supplier",
  "Hospice",
  "Hot dog stand",
  "Hot tub repair service",
  "Hot water system supplier",
  "Hub cap supplier",
  "Hunting area",
  "Hunting preserve",
  "Hydraulic engineer",
  "Hydraulic equipment supplier",
  "Hydraulic repair service",
  "Hydroponics equipment supplier",
  "Hypnotherapy service",
  "Ice cream equipment supplier",
  "Ice supplier",
  "Immigration & naturalization service",
  "Immigration detention center",
  "Impermeabilization service",
  "Incense supplier",
  "Income tax help association",
  "Industrial design company",
  "Industrial engineer",
  "Industrial engineers association",
  "Industrial equipment supplier",
  "Industrial gas supplier",
  "Industrial technical engineers association",
  "Industrial vacuum equipment supplier",
  "Information services",
  "Insolvency service",
  "Instrumentation engineer",
  "Insulator supplier",
  "Insurance company",
  "Intensivist",
  "Interior Decorator",
  "Interior designer",
  "Internal medicine ward",
  "Internet service provider",
  "Investment company",
  "Investment service",
  "Invitation printing service",
  "Iron works",
  "Irrigation equipment supplier",
  "IV therapy service",
  "Janitorial equipment supplier",
  "Jeweler",
  "Jewelry appraiser",
  "Jewelry buyer",
  "Jewelry designer",
  "Jewelry engraver",
  "Jewelry equipment supplier",
  "Jewelry repair service",
  "Joiner",
  "Judicial auction",
  "Junk removal service",
  "Juvenile detention center",
  "Kennel",
  "Kerosene supplier",
  "Key duplication service",
  "Lactation service",
  "Ladder supplier",
  "Laminating equipment supplier",
  "Lamination service",
  "Lamp repair service",
  "Lamp shade supplier",
  "Land surveying office",
  "Landscape designer",
  "Landscape lighting designer",
  "Landscaper",
  "Lapidary",
  "Laser cutting service",
  "Laser equipment supplier",
  "Laser hair removal service",
  "Laser tag center",
  "Laundry service",
  "Learning center",
  "Leasing service",
  "Leather goods supplier",
  "Leather repair service",
  "Legal services",
  "Leisure center",
  "Library",
  "License bureau",
  "License plate frames supplier",
  "Lido",
  "Life coach",
  "Light bulb supplier",
  "Limousine service",
  "Line marking service",
  "Liquidator",
  "Literacy program",
  "Livery company",
  "Livestock breeder",
  "Livestock producer",
  "Local government office",
  "Local medical services",
  "Locks supplier",
  "Loctician service",
  "Logistics service",
  "Longarm quilting service",
  "Lost property office",
  "LPG conversion",
  "Luggage repair service",
  "Luggage storage facility",
  "Machine construction",
  "Machine knife supplier",
  "Machine repair service",
  "Mailbox rental service",
  "Mailbox supplier",
  "Mailing machine supplier",
  "Mailing service",
  "Main customs office",
  "Mammography service",
  "Maori organization",
  "Mapping service",
  "Marae",
  "Marble supplier",
  "Marina",
  "Marine engineer",
  "Marine self defense force",
  "Marquee hire service",
  "Marriage celebrant",
  "Marriage or relationship counselor",
  "Marriage license bureau",
  "Masonic center",
  "Material handling equipment supplier",
  "Measuring instruments supplier",
  "Meat packer",
  "Faculty of media and information science",
  "Media company",
  "Mediation service",
  "Medical billing service",
  "Medical Center",
  "Medical certificate service",
  "Medical diagnostic imaging center",
  "Medical equipment supplier",
  "Medical group",
  "Medical office",
  "Medical transcription service",
  "Meditation center",
  "Meeting planning service",
  "Mehndi designer",
  "Memorial",
  "Men's tailor",
  "Mental health service",
  "Mercantile development",
  "Metal construction company",
  "Metal detecting equipment supplier",
  "Metal fabricator",
  "Metal finisher",
  "Metal heat treating service",
  "Metal industry suppliers",
  "Metal machinery supplier",
  "Metal polishing service",
  "Metal stamping service",
  "Metal supplier",
  "Metallurgy company",
  "Metalware producer",
  "Metropolitan train company",
  "Microwave oven repair service",
  "Military archive",
  "Military base",
  "Military board",
  "Military cemetery",
  "Military recruiting office",
  "Mine",
  "Mineral water company",
  "Mining company",
  "Mining engineer",
  "Mining equipment",
  "Missing persons organization",
  "Mobile caterer",
  "Mobile disco service",
  "Mobile network operator",
  "Mobility equipment supplier",
  "Model design company",
  "Mohel",
  "Molding supplier",
  "Money order service",
  "Money transfer service",
  "Monogramming service",
  "Mortuary",
  "Moving and storage service",
  "Moving company",
  "MRI center",
  "Mulch supplier",
  "Municipal administration office",
  "Municipal Guard",
  "Musalla",
  "Nail salon",
  "Nanotechnology engineering service",
  "National library",
  "National reserve",
  "Natural stone supplier",
  "Nature preserve",
  "Naturopathic practitioner",
  "Naval base",
  "News service",
  "Non-governmental organization",
  "Non-profit organization",
  "Notaries association",
  "Nuclear engineering service",
  "Nuclear power company",
  "Nursing association",
  "Occupational health service",
  "Occupational safety and health",
  "Off roading area",
  "Office equipment rental service",
  "Office equipment repair service",
  "Office equipment supplier",
  "Office refurbishment service",
  "Oil and gas exploration service",
  "Oil change service",
  "Oil & natural gas company",
  "Olive oil bottling company",
  "Olive oil cooperative",
  "Opera company",
  "Optical instrument repair service",
  "Orchid grower",
  "Orphanage",
  "Orthotics & prosthetics service",
  "Outdoor activity organiser",
  "Outdoor bath",
  "Outdoor equestrian facility",
  "Oxygen equipment supplier",
  "Oyster supplier",
  "Pachinko parlor",
  "Package locker",
  "Packaging company",
  "Paint stripping service",
  "Paintball center",
  "Painter",
  "Painting",
  "Pallet supplier",
  "Paper bag supplier",
  "Paper distributor",
  "Paper shredding machine supplier",
  "Paralegal services provider",
  "Parasailing ride operator",
  "Party equipment rental service",
  "Party planner",
  "Patent office",
  "Paternity testing service",
  "Patio enclosure supplier",
  "Paving materials supplier",
  "Payroll service",
  "Pension office",
  "Performing arts group",
  "Perinatal center",
  "Personal chef service",
  "Personal concierge service",
  "Personal trainer",
  "Pest control service",
  "Pet adoption service",
  "Pet boarding service",
  "Pet cemetery",
  "Pet funeral service",
  "Pet moving service",
  "Pet trainer",
  "Petrochemical engineering service",
  "Petroleum products company",
  "Pharmaceutical company",
  "Phone repair service",
  "Photo booth",
  "Photo restoration service",
  "Photographer",
  "Photography service",
  "Physical rehabilitation center",
  "Physiotherapy equipment supplier",
  "Piano moving service",
  "Piano repair service",
  "Piano tuning service",
  "Pile driving service",
  "Pilgrimage place",
  "Piñatas supplier",
  "Pinball machine supplier",
  "Pipe supplier",
  "Plastic bag supplier",
  "Plastic fabrication company",
  "Plastic injection molding service",
  "Plastic products supplier",
  "Plating service",
  "Plywood supplier",
  "Pneumatic tools supplier",
  "Political party office",
  "Polygraph service",
  "Polymer supplier",
  "Polythene and plastic sheeting supplier",
  "Pond fish supplier",
  "Pony ride service",
  "Post office",
  "Powder coating service",
  "Prawn fishing",
  "Precision engineer",
  "Japanese prefecture government office",
  "Printer repair service",
  "Printing equipment supplier",
  "Prison",
  "Private equity firm",
  "Private investigator",
  "Probation office",
  "Process server",
  "Foie gras producer",
  "Professional and hobby associations",
  "Professional association",
  "Professional organizer",
  "Promenade",
  "Promotional products supplier",
  "Propane supplier",
  "Property administration service",
  "Property investment company",
  "Property management company",
  "Protected area",
  "Psychic",
  "Psychosomatic medical practitioner",
  "Pump supplier",
  "Pumpkin patch",
  "PVC windows supplier",
  "Pyrotechnician",
  "Quarry",
  "Radiator repair service",
  "Rafting",
  "Railway services",
  "Rainwater tank supplier",
  "Ranch",
  "Ready mix concrete supplier",
  "Record company",
  "Records storage facility",
  "Recreation center",
  "Rectory",
  "Reenactment site",
  "Refrigerator repair service",
  "Regional government office",
  "Registration office",
  "Rehabilitation center",
  "Religious organization",
  "Repair service",
  "Research and product development",
  "Research engineer",
  "Research foundation",
  "Residents association",
  "Rest stop",
  "Resume service",
  "Retaining wall supplier",
  "Retirement community",
  "Rideshare pickup location",
  "Road construction company",
  "Road construction machine repair service",
  "Rodeo",
  "Rolled metal products supplier",
  "Rowing area",
  "Rubber products supplier",
  "RV detailing service",
  "RV inspection service",
  "RV storage facility",
  "Sacem",
  "Saddlery",
  "Safety equipment supplier",
  "Sailing event area",
  "Sand & gravel supplier",
  "Sandblasting service",
  "Sanitary inspection",
  "Sanitation service",
  "Satellite communication service",
  "Saw sharpening service",
  "Scaffolding service",
  "Scaffolding rental service",
  "Scale repair service",
  "Scale supplier",
  "Scenography company",
  "Scientific equipment supplier",
  "Scooter rental service",
  "Scouting",
  "Screen printer",
  "Screen repair service",
  "Screw supplier",
  "Seaplane base",
  "Seating systems provider",
  "Security guard service",
  "Security service",
  "Security system installation service",
  "Security system supplier",
  "Seed supplier",
  "Seitai",
  "Self-storage facility",
  "Semi conductor supplier",
  "Senior citizen center",
  "Septic system service",
  "Sewage disposal service",
  "Sewing company",
  "Sewing machine repair service",
  "Shared-use commercial kitchen",
  "Sharpening service",
  "Sheep shearer",
  "Sheepskin and wool products supplier",
  "Shelter",
  "Sheriff's department",
  "Shipping and mailing service",
  "Shipping company",
  "Shipping equipment industry",
  "Shipping service",
  "Shoe shining service",
  "Shooting event area",
  "Shooting range",
  "Shredding service",
  "Singing telegram service",
  "Singles organization",
  "Skate sharpening service",
  "Skeet shooting range",
  "Ski rental service",
  "Ski repair service",
  "Skydiving center",
  "Snow removal service",
  "Snowboard rental service",
  "Snowmobile rental service",
  "Social security financial department",
  "Social security office",
  "Social services organization",
  "Social welfare center",
  "Social worker",
  "Societe de Flocage",
  "Sod supplier",
  "Software company",
  "Soil testing service",
  "Solar energy company",
  "Solar energy system service",
  "Solar energy equipment supplier",
  "Solar hot water system supplier",
  "Solid fuel company",
  "Solid waste engineer",
  "Soup kitchen",
  "Spiritist center",
  "Spring supplier",
  "Stable",
  "Stall installation service",
  "Staple food package",
  "State archive",
  "State employment department",
  "State government office",
  "Statuary",
  "STD testing service",
  "Steel construction company",
  "Steel distributor",
  "Steel erector",
  "Steel fabricator",
  "Steelwork design service",
  "Stereo repair service",
  "Stone cutter",
  "Stone supplier",
  "Storage facility",
  "Structural engineer",
  "Students parents association",
  "Studying center",
  "Stylist",
  "Suburban train line",
  "Sugar shack",
  "Summer toboggan run",
  "Superfund site",
  "Surgical center",
  "Taekwondo competition area",
  "Tailor",
  "Tanning salon",
  "Tattoo removal service",
  "Tax collector's office",
  "Tax department",
  "Tax preparation",
  "Tax preparation service",
  "Teeth whitening service",
  "Telecommunications engineer",
  "Telecommunications equipment supplier",
  "Telecommunications service provider",
  "Telephone answering service",
  "Telephone company",
  "Telephone exchange",
  "Tenant ownership",
  "Tent rental service",
  "Test preparation center",
  "Textile engineer",
  "Theatrical costume supplier",
  "Thermal baths",
  "Thread supplier",
  "3D printing service",
  "Ticket office",
  "Tiffin center",
  "Tire service",
  "Title company",
  "Tobacco supplier",
  "Toll road rest stop",
  "Tool rental service",
  "Topography company",
  "Topsoil supplier",
  "Towing equipment provider",
  "Towing service",
  "Toy library",
  "Traffic officer",
  "Trailer rental service",
  "Train depot",
  "Train repairing center",
  "Train ticket office",
  "Transcription service",
  "Transit depot",
  "Translation service",
  "Tree service",
  "Tribal headquarters",
  "Truck parts supplier",
  "Truck stop",
  "Truck topper supplier",
  "Trucking company",
  "Tune up supplier",
  "Turf supplier",
  "Turnery",
  "Typewriter repair service",
  "Typewriter supplier",
  "Typing service",
  "Unemployment office",
  "Hairdresser",
  "United States Armed Forces Base",
  "Academic department",
  "Urban planning department",
  "Vacuum cleaning system supplier",
  "VCR repair service",
  "Vehicle inspection service",
  "Vehicle wrapping service",
  "Vending machine supplier",
  "Venture capital company",
  "Veterans center",
  "Veterans organization",
  "Veterinarian",
  "Video camera repair service",
  "Video conferencing equipment supplier",
  "Video conferencing service",
  "Video duplication service",
  "Video editing service",
  "Video equipment repair service",
  "Virtual office rental",
  "Visitor center",
  "Volunteer organization",
  "Voter registration office",
  "Washer & dryer repair service",
  "Waste management service",
  "Watch repair service",
  "Water cooler supplier",
  "Water damage restoration service",
  "Water filter supplier",
  "Water jet cutting service",
  "Water pump supplier",
  "Water purification company",
  "Water skiing service",
  "Water softening equipment supplier",
  "Water tank cleaning service",
  "Water testing service",
  "Water treatment supplier",
  "Water utility company",
  "Water works",
  "Water works equipment supplier",
  "Waterbed repair service",
  "Waterproofing service",
  "Wax supplier",
  "Waxing hair removal service",
  "Weather forecast service",
  "Web hosting company",
  "Website designer",
  "Wedding dress rental service",
  "Wedding photographer",
  "Wedding planner",
  "Wedding service",
  "Weight loss service",
  "Weir",
  "Welding gas supplier",
  "Wellness center",
  "Wellness program",
  "Wheel alignment service",
  "Wheelchair rental service",
  "Wheelchair repair service",
  "Wholesale jeweler",
  "Wildlife refuge",
  "Wildlife rescue service",
  "Window installation service",
  "Window supplier",
  "Window tinting service",
  "Wine cellar",
  "Wine storage facility",
  "Winery",
  "Wire and cable supplier",
  "Women's organization",
  "Women's personal trainer",
  "Women's protection service",
  "Women's shelter",
  "Wood and laminate flooring supplier",
  "Wood floor installation service",
  "Wood floor refinishing service",
  "Wood frame supplier",
  "Wood supplier",
  "X-ray equipment supplier",
  "Youth center",
  "Youth group",
  "Youth organization",
  "Youth social services organization"
];
